### ISSUE TITLE
client.py error

### ISSUE THREAD

**Issue by gra1w** [malwaredllc/byob#104]
Can anyone help me?

182 INFO: PyInstaller: 3.3.1
182 INFO: Python: 2.7.16
182 INFO: Platform: Windows-10-10.0.17763
183 INFO: UPX is not available.
Traceback (most recent call last):
  File "C:\Python27\Lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "C:\Python27\Lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Python27\lib\site-packages\PyInstaller\__main__.py", line 101, in <module>
    run()
  File "C:\Python27\lib\site-packages\PyInstaller\__main__.py", line 94, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "C:\Python27\lib\site-packages\PyInstaller\__main__.py", line 46, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "C:\Python27\lib\site-packages\PyInstaller\building\build_main.py", line 791, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "C:\Python27\lib\site-packages\PyInstaller\building\build_main.py", line 737, in build
    exec(text, spec_namespace)
  File "<string>", line 2, in <module>
  File "C:\Python27\lib\site-packages\PyInstaller\archive\pyz_crypto.py", line 54, in __init__
    self._aesmod = import_aes(get_crypto_hiddenimports())
  File "C:\Python27\lib\site-packages\PyInstaller\archive\pyz_crypto.py", line 37, in get_crypto_hiddenimports
    import_aes(modname)
  File "C:\Python27\lib\site-packages\PyInstaller\archive\pyz_crypto.py", line 21, in import_aes
    return __import__(module_name, fromlist=[module_name.split('.')[-1]])
ImportError: No module named Crypto.Cipher.AES

**Comment by malwaredllc** [comment]
You need install PyCrypto (or pycryptodomex) in order to encrypt the code you're compiling with PyInstaller.

So run: `pip install pycrypto' then it should work.
