### ISSUE TITLE
Socket binding of server is not working at all.

### ISSUE THREAD

**Issue by TormentedSoul666** [malwaredllc/byob#132]
Do you even test your stuff?
calling python3 server.php doesn't even start a service on 1337

cat temp:
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/lib/python3.5/http/server.py", line 1221, in <module>
    test(HandlerClass=handler_class, port=args.port, bind=args.bind)
  File "/usr/lib/python3.5/http/server.py", line 1194, in test
    httpd = ServerClass(server_address, HandlerClass)
  File "/usr/lib/python3.5/socketserver.py", line 440, in __init__
    self.server_bind()
  File "/usr/lib/python3.5/http/server.py", line 138, in server_bind
    socketserver.TCPServer.server_bind(self)
  File "/usr/lib/python3.5/socketserver.py", line 454, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 98] Address already in use
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/lib/python3.5/http/server.py", line 1221, in <module>
    test(HandlerClass=handler_class, port=args.port, bind=args.bind)
  File "/usr/lib/python3.5/http/server.py", line 1194, in test
    httpd = ServerClass(server_address, HandlerClass)
  File "/usr/lib/python3.5/socketserver.py", line 440, in __init__
    self.server_bind()
  File "/usr/lib/python3.5/http/server.py", line 138, in server_bind
    socketserver.TCPServer.server_bind(self)
  File "/usr/lib/python3.5/socketserver.py", line 454, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 98] Address already in use
Traceback (most recent call last):
  File "core/handler.py", line 54, in <module>
    main()
  File "core/handler.py", line 51, in main
    run(port=port)
  File "core/handler.py", line 45, in run
    httpd = server_class(('0.0.0.0', port), handler_class)
  File "/usr/lib/python3.5/socketserver.py", line 440, in __init__
    self.server_bind()
  File "/usr/lib/python3.5/http/server.py", line 138, in server_bind
    socketserver.TCPServer.server_bind(self)
  File "/usr/lib/python3.5/socketserver.py", line 454, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 98] Address already in use

Same is happening with Python2. I suspect the "httpd.serve_forever()" but the server never establish a working socket on port 1337, even with the first run.

**Comment by TormentedSoul666** [comment]
Lol.
python2 server.py

ps aux:
root      5735  0.0  0.1   4504   744 pts/0    S    14:21   0:00 /bin/sh -c /usr/bin/python3 -m http.server 1339
root      5736  0.0  0.1   4504   696 pts/0    S    14:21   0:00 /bin/sh -c /usr/bin/python3 -m http.server 1338
root      5737  0.7  3.3  58044 16892 pts/0    S    14:21   0:00 /usr/bin/python3 -m http.server 1339
root      5738  0.0  0.1   4504   696 pts/0    S    14:21   0:00 /bin/sh -c /usr/bin/python3 core/handler.py 1340
root      5739  0.6  3.3  58096 16960 pts/0    S    14:21   0:00 /usr/bin/python3 -m http.server 1338
root      5741  0.6  3.3  60000 16792 pts/0    S    14:21   0:00 /usr/bin/python3 core/handler.py 1340

**Comment by TormentedSoul666** [comment]
So with this code it's impossible to get a working C2 and when you exit the server and restart it, it even gets worse.
It's a pitty.

**Comment by intrct** [comment]
This is not a universal issue. The application was not designed for python 3, but it has been partially refitted for 3.6+. 

You're using 3.5, so I suggest getting a newer version.
