### ISSUE TITLE
Install in Windows

### ISSUE THREAD

**Issue by MircoCagni** [malwaredllc/byob#157]
Becouse I cant generate an .exe file from linux machine (maybe is better do a future update for this) i try to use client.py in windows.  When i run
When i run it:
`PS C:\Users\Mirco\AppData\Local\Programs\Python\Python38-32> .\python.exe .\byob-master\byob\client.py 79.143.186.34 8080 --freeze`

I had try to install requirements with pip and that is result:
```
`
PS C:\Users\Mirco\AppData\Local\Programs\Python\Python38-32> .\Scripts\pip.exe install -r .\byob-master\byob\requirements.txt
Ignoring opencv-python: markers 'python_version < "3"' don't match your environment
Collecting mss==3.3.0
  Using cached https://files.pythonhosted.org/packages/d1/bc/1965b94c015666f0dce53248e219802137cfe3927109843706d7c4c48f78/mss-3.3.0-py2.py3-none-any.whl
Collecting WMI==1.4.9
  Using cached https://files.pythonhosted.org/packages/03/2d/cbf13257c0115bef37b6b743758411cec70c565405cbd08d0f7059bc715f/WMI-1.4.9.zip
Collecting numpy==1.15.2
  Using cached https://files.pythonhosted.org/packages/45/ba/2a781ebbb0cd7962cc1d12a6b65bd4eff57ffda449fdbbae4726dc05fbc3/numpy-1.15.2.zip
Collecting pyxhook==1.0.0
  Using cached https://files.pythonhosted.org/packages/70/d1/8f56e13b002502ad85975f2dcebb5d1026551e34cafc77ae70a294a67eed/pyxhook-1.0.0.tar.gz
Collecting twilio==6.14.0
  Using cached https://files.pythonhosted.org/packages/4c/b5/f341339851a53a76dd476979f5a67595990d9d45417b1cd65c140154ae4b/twilio-6.14.0-py2.py3-none-any.whl
Collecting colorama==0.3.9
  Using cached https://files.pythonhosted.org/packages/db/c8/7dcf9dbcb22429512708fe3a547f8b6101c0d02137acbd892505aee57adf/colorama-0.3.9-py2.py3-none-any.whl
Collecting requests==2.20.0
  Using cached https://files.pythonhosted.org/packages/f1/ca/10332a30cb25b627192b4ea272c351bce3ca1091e541245cccbace6051d8/requests-2.20.0-py2.py3-none-any.whl
Collecting PyInstaller==3.3.1
  Using cached https://files.pythonhosted.org/packages/3c/86/909a8c35c5471919b3854c01f43843d9b5aed0e9948b63e560010f7f3429/PyInstaller-3.3.1.tar.gz
Collecting pycryptodomex==3.8.1
  Using cached https://files.pythonhosted.org/packages/05/86/92b303bc4ed00451401e99e90003d5361fb054b9af9af2490b1b44caeaef/pycryptodomex-3.8.1.tar.gz
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\mirco\appdata\local\programs\python\python38-32\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Mirco\\AppData\\Local\\Temp\\pip-install-e9gnouj4\\pycryptodomex\\setup.py'"'"'; __file__='"'"'C:\\Users\\Mirco\\AppData\\Local\\Temp\\pip-install-e9gnouj4\\pycryptodomex\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\Mirco\AppData\Local\Temp\pip-install-e9gnouj4\pycryptodomex\pip-egg-info'
         cwd: C:\Users\Mirco\AppData\Local\Temp\pip-install-e9gnouj4\pycryptodomex\
    Complete output (31 lines):
    Traceback (most recent call last):
      File "c:\users\mirco\appdata\local\programs\python\python38-32\lib\site-packages\setuptools\msvc.py", line 489, in _find_latest_available_vc_ver
        return self.find_available_vc_vers()[-1]
    IndexError: list index out of range

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\Mirco\AppData\Local\Temp\pip-install-e9gnouj4\pycryptodomex\setup.py", line 443, in <module>
        set_compiler_options(package_root, ext_modules)
      File "C:\Users\Mirco\AppData\Local\Temp\pip-install-e9gnouj4\pycryptodomex\compiler_opt.py", line 304, in set_compiler_options
        clang = compiler_is_clang()
      File "C:\Users\Mirco\AppData\Local\Temp\pip-install-e9gnouj4\pycryptodomex\compiler_opt.py", line 239, in compiler_is_clang
        return test_compilation(source, msg="clang")
      File "C:\Users\Mirco\AppData\Local\Temp\pip-install-e9gnouj4\pycryptodomex\compiler_opt.py", line 82, in test_compilation
        objects = compiler.compile([fname], extra_postargs=extra_cc_options)
      File "c:\users\mirco\appdata\local\programs\python\python38-32\lib\distutils\_msvccompiler.py", line 360, in compile
        self.initialize()
      File "c:\users\mirco\appdata\local\programs\python\python38-32\lib\distutils\_msvccompiler.py", line 253, in initialize
        vc_env = _get_vc_env(plat_spec)
      File "c:\users\mirco\appdata\local\programs\python\python38-32\lib\site-packages\setuptools\msvc.py", line 185, in msvc14_get_vc_env
        return EnvironmentInfo(plat_spec, vc_min_ver=14.0).return_env()
      File "c:\users\mirco\appdata\local\programs\python\python38-32\lib\site-packages\setuptools\msvc.py", line 843, in __init__
        self.si = SystemInfo(self.ri, vc_ver)
      File "c:\users\mirco\appdata\local\programs\python\python38-32\lib\site-packages\setuptools\msvc.py", line 485, in __init__
        self.vc_ver = vc_ver or self._find_latest_available_vc_ver()
      File "c:\users\mirco\appdata\local\programs\python\python38-32\lib\site-packages\setuptools\msvc.py", line 492, in _find_latest_available_vc_ver
        raise distutils.errors.DistutilsPlatformError(err)
    distutils.errors.DistutilsPlatformError: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": https://visualstudio.microsoft.com/downloads/
    Testing support for clang
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
PS C:\Users\Mirco\AppData\Local\Programs\Python\Python38-32>
`
```
```

When i use python setup.py egg_info
`PS C:\Users\Mirco\AppData\Local\Programs\Python\Python38-32> .\python.exe .\byob-master\byob\setup.py egg_info
INFORMAZIONI: impossibile trovare file corrispondenti ai
criteri di ricerca indicati.
DEBUG:__main__:Error in pip package installer: Command 'where pip' returned non-zero exit status 1.
Installing requirements.txt
Ignoring opencv-python: markers 'python_version < "3"' don't match your environment

Collecting mss==3.3.0

  Using cached https://files.pythonhosted.org/packages/d1/bc/1965b94c015666f0dce53248e219802137cfe3927109843706d7c4c48f78/mss-3.3.0-py2.py3-none-any.whl

Collecting WMI==1.4.9

  Using cached https://files.pythonhosted.org/packages/03/2d/cbf13257c0115bef37b6b743758411cec70c565405cbd08d0f7059bc715f/WMI-1.4.9.zip

Collecting numpy==1.15.2

  Using cached https://files.pythonhosted.org/packages/45/ba/2a781ebbb0cd7962cc1d12a6b65bd4eff57ffda449fdbbae4726dc05fbc3/numpy-1.15.2.zip

Collecting pyxhook==1.0.0

  Using cached https://files.pythonhosted.org/packages/70/d1/8f56e13b002502ad85975f2dcebb5d1026551e34cafc77ae70a294a67eed/pyxhook-1.0.0.tar.gz

Collecting twilio==6.14.0

  Using cached https://files.pythonhosted.org/packages/4c/b5/f341339851a53a76dd476979f5a67595990d9d45417b1cd65c140154ae4b/twilio-6.14.0-py2.py3-none-any.whl

Collecting colorama==0.3.9

  Using cached https://files.pythonhosted.org/packages/db/c8/7dcf9dbcb22429512708fe3a547f8b6101c0d02137acbd892505aee57adf/colorama-0.3.9-py2.py3-none-any.whl

Collecting requests==2.20.0

  Using cached https://files.pythonhosted.org/packages/f1/ca/10332a30cb25b627192b4ea272c351bce3ca1091e541245cccbace6051d8/requests-2.20.0-py2.py3-none-any.whl

Collecting PyInstaller==3.3.1

  Using cached https://files.pythonhosted.org/packages/3c/86/909a8c35c5471919b3854c01f43843d9b5aed0e9948b63e560010f7f3429/PyInstaller-3.3.1.tar.gz

```
Collecting pycryptodomex==3.8.1

  Using cached https://files.pythonhosted.org/packages/05/86/92b303bc4ed00451401e99e90003d5361fb054b9af9af2490b1b44caeaef/pycryptodomex-3.8.1.tar.gz

PS C:\Users\Mirco\AppData\Local\Programs\Python\Python38-32>`

**Comment by jchernin4** [comment]
Read the logs it tells you the exact solution

**Comment by MircoCagni** [comment]
> Read the logs it tells you the exact solution

I had read but I dont understand how resolve. Can u help me please?

**Comment by Infinium1** [comment]
Reread the first code box you sent. It gives you the problem and the link to fix it

**Comment by Infinium1** [comment]
This is a separate thing but use python 2.7 but the other part you can figure out easily if you read the last few lines of the first box

**Comment by mrfr05t** [comment]
Use python vc++ build tools
