### ISSUE TITLE
connection timed out

### ISSUE THREAD

**Issue by Ilori-Jaiyeola** [malwaredllc/byob#160]
Traceback (most recent call last):
  File "server.py", line 896, in __init__
    self.info = self.client_info()
  File "server.py", line 926, in client_info
    if bytes(val).startswith("_b64"):
TypeError: string argument without an encoding

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "server.py", line 781, in serve_until_stopped
    session = Session(connection=connection, id=self._count)
  File "server.py", line 899, in __init__
    print(bytes(e))
TypeError: cannot convert 'TypeError' object to bytes

**Comment by jchernin4** [comment]
Try using python 2.7

**Comment by Ilori-Jaiyeola** [comment]
It worked with python2.7
thanks

**Comment by Infinium1** [comment]
No problem! Make sure you close the issue if it is resolved
