### ISSUE TITLE
Can't get client.py to create exe (UPX is not available)

### ISSUE THREAD

**Issue by malweghorst** [malwaredllc/byob#171]
C:\Users\Tollg\byob\byob>python client.py IP Port --freeze

88                                  88
88                                  88
88                                  88
88,dPPYba,  8b       d8  ,adPPYba,  88,dPPYba,
88P'    "8a `8b     d8' a8"     "8a 88P'    "8a
88       d8  `8b   d8'  8b       d8 88       d8
88b,   ,a8"   `8b,d8'   "8a,   ,a8" 88b,   ,a8"
8Y"Ybbd8"'      Y88'     `"YbbdP"'  8Y"Ybbd8"'
                d8'
               d8'

[>] Modules
        Adding modules...  (3 modules added to client)

[>] Imports
        Adding imports... (26 imports from 3 modules)

[>] Payload
        Uploading payload...  (hosting payload at: http://IP:Port///payloads/dOI.py)

[>] Stager
        Uploading stager...  (hosting stager at: http://IP:Port///stagers/dOI.py)

[>] Dropper
        Writing dropper...  (343 bytes written to byob_dOI.py)
        Compiling executable...
 53 INFO: PyInstaller: 3.5
53 INFO: Python: 3.8.0
53 INFO: Platform: Windows-10-10.0.17763-SP0
54 INFO: UPX is not available.
Traceback (most recent call last):
  File "C:\Users\Tollg\AppData\Local\Programs\Python\Python38\lib\site-packages\PyInstaller\archive\pyz_crypto.py", line 33, in get_crypto_hiddenimports
    import_aes(modname)
  File "C:\Users\Tollg\AppData\Local\Programs\Python\Python38\lib\site-packages\PyInstaller\archive\pyz_crypto.py", line 21, in import_aes
    return __import__(module_name, fromlist=[module_name.split('.')[-1]])
ModuleNotFoundError: No module named 'Crypto'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Tollg\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 192, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Tollg\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Tollg\AppData\Local\Programs\Python\Python38\lib\site-packages\PyInstaller\__main__.py", line 118, in <module>
    run()
  File "C:\Users\Tollg\AppData\Local\Programs\Python\Python38\lib\site-packages\PyInstaller\__main__.py", line 111, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "C:\Users\Tollg\AppData\Local\Programs\Python\Python38\lib\site-packages\PyInstaller\__main__.py", line 63, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "C:\Users\Tollg\AppData\Local\Programs\Python\Python38\lib\site-packages\PyInstaller\building\build_main.py", line 844, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "C:\Users\Tollg\AppData\Local\Programs\Python\Python38\lib\site-packages\PyInstaller\building\build_main.py", line 791, in build
    exec(code, spec_namespace)
  File "/Users/Tollg/byob/byob\byob_dOI.spec", line 2, in <module>
    block_cipher = pyi_crypto.PyiBlockCipher(key='nt=PZ0ONp@Vx4lW>')
  File "C:\Users\Tollg\AppData\Local\Programs\Python\Python38\lib\site-packages\PyInstaller\archive\pyz_crypto.py", line 54, in __init__
    self._aesmod = import_aes(get_crypto_hiddenimports())
  File "C:\Users\Tollg\AppData\Local\Programs\Python\Python38\lib\site-packages\PyInstaller\archive\pyz_crypto.py", line 37, in get_crypto_hiddenimports
    import_aes(modname)
  File "C:\Users\Tollg\AppData\Local\Programs\Python\Python38\lib\site-packages\PyInstaller\archive\pyz_crypto.py", line 21, in import_aes
    return __import__(module_name, fromlist=[module_name.split('.')[-1]])
ModuleNotFoundError: No module named 'Crypto'

**Comment by malwaredllc** [comment]
The last line at the bottom (`ModuleNotFoundError: No module named 'Crypto'`) indiciates you need to install the python library pycryptodomex (it is required to encrypt the payloads).
To do this, you can run the `setup.py` script in the root `/byob` directory and it will install all the required packages for you.
