### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe4 in position 40: invalid continuation byte

### ISSUE THREAD

**Issue by fabilus11** [malwaredllc/byob#176]
I´ve tried to get it to work on windows ´cause I had some problems but fixed them.. but now I cant get this to work I tried to fix it myself but can´t find any solution...
```
Traceback (most recent call last):
  File "C:\Users\X\Desktop\venv\lib\site-packages\win32ctypes\pywin32\pywintypes.py", line 35, in pywin32error
    yield
  File "C:\Users\X\Desktop\venv\lib\site-packages\win32ctypes\pywin32\win32api.py", line 43, in LoadLibraryEx
    return _dll._LoadLibraryEx(fileName, 0, flags)
  File "C:\Users\X\Desktop\venv\lib\site-packages\win32ctypes\core\cffi\_dll.py", line 26, in _LoadLibraryEx
    function_name='LoadLibraryEx')
  File "C:\Users\X\Desktop\venv\lib\site-packages\win32ctypes\core\cffi\_util.py", line 81, in __call__
    self._raise_error(function_name)
  File "C:\Users\X\Desktop\venv\lib\site-packages\win32ctypes\core\cffi\_util.py", line 92, in _raise_error
    raise exception
Traceback (most recent call last):
  File "client.py", line 438, in <module>
    main()
  File "client.py", line 192, in main
    dropper = _dropper(options, var=var, key=key, modules=modules, imports=imports, hidden=hidden, url=stager)
  File "client.py", line 420, in _dropper
    name = generators.freeze(name, icon=options.icon, hidden=kwargs['hidden'])
  File "C:\Users\X\Desktop\byob-master\byob\core\generators.py", line 246, in freeze
    util.display(line, color='reset', style='dim')
  File "core\util.py", line 399, in display
    output = output.decode('utf-8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe4 in position 40: invalid continuation byte
```

**Comment by fabilus11** [comment]
so I tried like 2 hours after posting this to fix this... I edit the code re edited it nothing... but hold on I fixed it... it was the --icon function i just needed to get rid of that so standart icon for me
