### ISSUE TITLE
python3 don't work

### ISSUE THREAD

**Issue by rasperepodvipodvert** [malwaredllc/byob#179]
```[root @ /home/user/byob/byob]>Exception in thread 1580727284.5890706:
Traceback (most recent call last):
  File "server.py", line 896, in __init__
    self.info = self.client_info()
  File "server.py", line 926, in client_info
    if bytes(val).startswith("_b64"):
TypeError: string argument without an encoding

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "server.py", line 781, in serve_until_stopped
    session = Session(connection=connection, id=self._count)
  File "server.py", line 899, in __init__
    print(bytes(e))
TypeError: cannot convert 'TypeError' object to bytes
```

**Comment by malwaredllc** [comment]
Yes the port to Python 3 is still in progress and not yet complete.

**Comment by malwaredllc** [comment]
@rasperepodvipodvert Python3 support has been added in #191
