### ISSUE TITLE
Shell isn´t working for me

### ISSUE THREAD

**Issue by fabilus11** [malwaredllc/byob#200]
I have finally connected to my VM and then I tried using the shell. my VM is windows 10
I used my local IP this time for the server and client

```
[37m[1m[fabia @ C:\Users\fabian\Desktop\byob]>shell 0


Starting Reverse TCP Shell w/ Session 0...

[37m[1m[ 0 @ C:\Users\fabi\Downloads ]>dir
Exception in thread 1586902237.517921:
Traceback (most recent call last):
  File "C:\Users\fabia\AppData\Local\Programs\Python\Python37\lib\threading.py", line 926, in _bootstrap_inner
    self.run()
  File "C:\Users\fabia\AppData\Local\Programs\Python\Python37\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "server.py", line 783, in serve_until_stopped
    info = self.database.handle_session(session.info)
  File "C:\Users\fabia\Desktop\byob\core\database.py", line 231, in handle_session
    buid = str(info['public_ip'] + info['mac_address']).encode()
KeyError: 'public_ip'

Session 0 disconnected
```

**Comment by fabilus11** [comment]
oh I see my mistake I just did some googling and stuff it there are just some cmd´s I can do oh.. nvm sorry for opening another issue
