### ISSUE TITLE
When's the support for python 3.8.5?

### ISSUE THREAD

**Issue by MiChaelinzo** [malwaredllc/byob#287]
```
/usr/bin/docker
(347 bytes written to output/user/src/byob_win_x32_eR1.py)
        Compiling executable...

b'0044:err:explorer:initialize_display_settings Failed to query current display settings for L"\\\\\\\\.\\\\DISPLAY1".'
b'007c:err:ntoskrnl:ZwLoadDriver failed to create driver L"\\\\Registry\\\\Machine\\\\System\\\\CurrentControlSet\\\\Services\\\\wineusb": c0000142'
b'WARNING: You are using pip version 20.2.2; however, version 20.2.3 is available.'
b"You should consider upgrading via the 'c:\\Python37\\python.exe -m pip install --upgrade pip' command."
b'00f4:err:winediag:load_gssapi_krb5 Failed to load libgssapi_krb5, Kerberos SSP support will not be available.'
b'827 INFO: PyInstaller: 3.6'
b'828 INFO: Python: 3.7.5'
b'828 INFO: Platform: Windows-7-6.1.7601-SP1'
b'840 INFO: UPX is not available.'
b'840 INFO: Removing temporary files and cleaning cache in C:\\users\\root\\Application Data\\pyinstaller'
b'855 INFO: Extending PYTHONPATH with paths'
b"['Z:\\\\src',"
b" 'Z:\\\\home\\\\user\\\\byob\\\\web-gui\\\\buildyourownbotnet\\\\output\\\\user\\\\src']"
b'855 INFO: checking Analysis'
b'855 INFO: Building Analysis because Analysis-00.toc is non existent'
b'855 INFO: Initializing module dependency graph...'
b'877 INFO: Caching module graph hooks...'
b'903 INFO: Analyzing base_library.zip ...'
b'9118 INFO: Caching module dependency graph...'
b'9725 INFO: running Analysis Analysis-00.toc'
b'9763 INFO: Adding Microsoft.Windows.Common-Controls to dependent assemblies of final executable'
b'  required by c:\\Python37\\python.exe'
b'10814 INFO: Analyzing byob_nix_amd64_atZ.py'
b"11233 INFO: Analyzing hidden import 'imp'"
b"11256 INFO: Analyzing hidden import 'requests'"
b'11759 INFO: Processing pre-safe import module hook   urllib3.packages.six.moves'
b"14909 INFO: Analyzing hidden import 'ctypes'"
b"15000 INFO: Analyzing hidden import 'pycryptonight'"
b"15011 ERROR: Hidden import 'pycryptonight' not found"
b"15011 INFO: Analyzing hidden import 'multiprocessing'"
b"15963 INFO: Analyzing hidden import 'pyrx'"
b"15975 ERROR: Hidden import 'pyrx' not found"
b"15976 INFO: Analyzing hidden import 'colorama'"
b"16125 INFO: Analyzing hidden import 'uuid'"
b"16399 INFO: Analyzing hidden import 'numpy'"
b'17693 INFO: Processing pre-find module path hook   distutils'
b"17701 INFO: distutils: retargeting to non-venv dir 'c:\\\\Python37\\\\lib'"
b'22107 INFO: Processing pre-safe import module hook   setuptools.extern.six.moves'
b'0114:err:winediag:load_gssapi_krb5 Failed to load libgssapi_krb5, Kerberos SSP support will not be available.'
b'29314 INFO: Processing module hooks...'
b'29314 INFO: Loading module hook "hook-certifi.py"...'
b'29341 INFO: Loading module hook "hook-distutils.py"...'
b'29348 INFO: Loading module hook "hook-encodings.py"...'
b'29933 INFO: Loading module hook "hook-lib2to3.py"...'
b'29987 INFO: Loading module hook "hook-numpy.core.py"...'
b'30745 INFO: Loading module hook "hook-numpy.py"...'
b'30753 INFO: Loading module hook "hook-pkg_resources.py"...'
b'0140:err:winediag:load_gssapi_krb5 Failed to load libgssapi_krb5, Kerberos SSP support will not be available.'
b'32952 INFO: Processing pre-safe import module hook   win32com'
b"33169 INFO: Excluding import '__main__'"
b'33171 INFO:   Removing import of __main__ from module pkg_resources'
b'33171 INFO: Loading module hook "hook-pydoc.py"...'
b'33185 INFO: Loading module hook "hook-pythoncom.py"...'
b'0148:err:winediag:load_gssapi_krb5 Failed to load libgssapi_krb5, Kerberos SSP support will not be available.'
b'35555 INFO: Loading module hook "hook-pywintypes.py"...'
b'0150:err:winediag:load_gssapi_krb5 Failed to load libgssapi_krb5, Kerberos SSP support will not be available.'
b'37966 INFO: Loading module hook "hook-setuptools.py"...'
b'0158:err:winediag:load_gssapi_krb5 Failed to load libgssapi_krb5, Kerberos SSP support will not be available.'
b'41258 INFO: Loading module hook "hook-sysconfig.py"...'
b'41265 INFO: Loading module hook "hook-win32com.py"...'
b'42319 INFO: Loading module hook "hook-xml.dom.domreg.py"...'
b'42327 INFO: Loading module hook "hook-xml.py"...'
b'42402 INFO: Looking for ctypes DLLs'
b'Traceback (most recent call last):'
b'  File "c:\\Python37\\lib\\runpy.py", line 193, in _run_module_as_main'
b'    "__main__", mod_spec)'
b'  File "c:\\Python37\\lib\\runpy.py", line 85, in _run_code'
b'    exec(code, run_globals)'
b'  File "C:\\Python37\\Scripts\\pyinstaller.exe\\__main__.py", line 7, in <module>'
b'  File "c:\\Python37\\lib\\site-packages\\PyInstaller\\__main__.py", line 114, in run'
b'    run_build(pyi_config, spec_file, **vars(args))'
b'  File "c:\\Python37\\lib\\site-packages\\PyInstaller\\__main__.py", line 65, in run_build'
b'    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)'
b'  File "c:\\Python37\\lib\\site-packages\\PyInstaller\\building\\build_main.py", line 734, in main'
b"    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))"
b'  File "c:\\Python37\\lib\\site-packages\\PyInstaller\\building\\build_main.py", line 681, in build'
b'    exec(code, spec_namespace)'
b'  File "byob_nix_amd64_atZ.spec", line 13, in <module>'
b'    cipher=block_cipher)'
b'  File "c:\\Python37\\lib\\site-packages\\PyInstaller\\building\\build_main.py", line 244, in __init__'
b'    self.__postinit__()'
b'  File "c:\\Python37\\lib\\site-packages\\PyInstaller\\building\\datastruct.py", line 160, in __postinit__'
b'    self.assemble()'
b'  File "c:\\Python37\\lib\\site-packages\\PyInstaller\\building\\build_main.py", line 436, in assemble'
b"    ctypes_code_objs = self.graph.get_co_using_ctypes()  # dict like:  {'module1': code_obj, 'module2': code_obj}"
b'  File "c:\\Python37\\lib\\site-packages\\PyInstaller\\depend\\analysis.py", line 674, in get_co_using_ctypes'
b'    r_ident =  r.identifier'
b"AttributeError: 'NoneType' object has no attribute 'identifier'"
b''

```
Linux 5.8.0-amd64 #1 SMP Debian 5.8.10(2020-09-22) x86_64 GNU/Linux
Python 3.8.5 version

**Comment by SkyBoltDom** [comment]
Use pip3

**Comment by MiChaelinzo** [comment]
> Use pip3

smh lmao i'm running web-gui already in python3, pip3 command if your going to install requirements etc.

**Comment by SkyBoltDom** [comment]
Are you using as root because some of the dependencies are needed as root

**Comment by SkyBoltDom** [comment]
I'm reading the first 2 lines and it says for you to upgrade so why don't you upgrade pip fist and post later. I'm sure you are smart figure it out. Also you are running on windows and the program was made on Linux so their might be compatibility issues

**Comment by SkyBoltDom** [comment]
You are missing a lot of dependencies for python so I suggest you install those.

**Comment by MiChaelinzo** [comment]
Bro I have all dependencies, installed it on pip3 etc. It's clearly that malwaredllc/byob/ only support for 3.7.5 and I don't want to downgrade I have alot of apps running in python 3.8. Compiling executable winx32 & i386 & amd64 bloats my docker containers and it's not even usable. Thank you for help & reply tho.

**Comment by Tiny-Lamma** [comment]
@MiChaelinzo, use venv
https://docs.python.org/3/tutorial/venv.html
