### ISSUE TITLE
the web-gui will start but them immediately close 

### ISSUE THREAD

**Issue by alide123321** [malwaredllc/byob#292]
the error message 
```
Step 25/25 : ENTRYPOINT ["/entrypoint.sh"]
 ---> Using cache
 ---> 7793a0ec1e5a
Successfully built 7793a0ec1e5a
Successfully tagged win-x32:latest
Running C2 server with locally hosted web app GUI...
Navigate to http://127.0.0.1:5000 and set up your user to get started.
Traceback (most recent call last):
  File "run.py", line 1, in <module>
    from buildyourownbotnet import app
  File "/opt/byob/web-gui/buildyourownbotnet/__init__.py", line 18, in <module>
    db = SQLAlchemy(app)
  File "/usr/lib/python3/dist-packages/flask_sqlalchemy/__init__.py", line 716, in __init__
    self.Model = self.make_declarative_base(model_class, metadata)
  File "/usr/lib/python3/dist-packages/flask_sqlalchemy/__init__.py", line 798, in make_declarative_base
    model.query_class = self.Query
  File "/usr/lib/python3/dist-packages/sqlalchemy/ext/declarative/api.py", line 79, in __setattr__
    _add_attribute(cls, key, value)
  File "/usr/lib/python3/dist-packages/sqlalchemy/ext/declarative/base.py", line 802, in _add_attribute
    type.__setattr__(cls, key, value)
TypeError: can't apply this __setattr__ to DefaultMeta object
root@kali-VM:/opt/byob/web-gui# 
```

**Comment by ricko2991** [comment]
Hi, install all requiremenst first before build docker image. and to start over from the first, delete all the installed images. For example: docker image rm <id> 
docker image ls => to list the image. 
Built docker just for linux container. Just comment or delete :
docker build -f Dockerfile-py3-win32 -t win-x32 .
**Locate on startup.sh**
