### ISSUE TITLE
byob installation issue kali linux 2020

### ISSUE THREAD

**Issue by jamesmiller9048** [malwaredllc/byob#299]
tried running all the files that were necessary but still can't get to web GUI
docker and python is already installed in my sys
first I tired to run startup.sh it was okay, then I ran run.py some errors were displaying
then I ran requirements.txt with python pip install, and then run.py but still there was error
then in some guides it was given to run the setup.sh first but there were no such file there so search other dir and found setup.py I ran that file also and then the run.py file again still error was poping
the error was pointing to init.py file

**Comment by ricko2991** [comment]
Hi, install all requirements.txt first and then run startup.sh, run.py will run automatically at startup.sh

**Comment by jamesmiller9048** [comment]
Yes I did that 
Sudo python3.7 pip -m intsall -r requirements.txt
Sudo ./startup.sh
Sudo python 3.7 ./run.py
Still error

**Comment by ricko2991** [comment]
what error did you have. can you give a screenshot?

**Comment by jamesmiller9048** [comment]
running it as non root user i get :-1 
bcrypt is required to use Flask-Bcrypt
Traceback (most recent call last):
  File "run.py", line 1, in <module>
    from buildyourownbotnet import app
  File "/home/kali/Desktop/byob/web-gui/buildyourownbotnet/__init__.py", line 4, in <module>
    from flask_bcrypt import Bcrypt
  File "/home/kali/.local/lib/python3.7/site-packages/flask_bcrypt.py", line 27, in <module>
    raise e
  File "/home/kali/.local/lib/python3.7/site-packages/flask_bcrypt.py", line 24, in <module>
    import bcrypt
  File "/usr/lib/python3/dist-packages/bcrypt/__init__.py", line 25, in <module>
    from . import _bcrypt
ModuleNotFoundError: No module named '_cffi_backend'

running it as root user i get the following error:-
bcrypt is required to use Flask-Bcrypt
Traceback (most recent call last):
  File "run.py", line 1, in <module>
    from buildyourownbotnet import app
  File "/home/kali/Desktop/byob/web-gui/buildyourownbotnet/__init__.py", line 4, in <module>
    from flask_bcrypt import Bcrypt
  File "/usr/local/lib/python3.7/dist-packages/flask_bcrypt.py", line 27, in <module>
    raise e
  File "/usr/local/lib/python3.7/dist-packages/flask_bcrypt.py", line 24, in <module>
    import bcrypt
  File "/usr/lib/python3/dist-packages/bcrypt/__init__.py", line 25, in <module>
    from . import _bcrypt
ModuleNotFoundError: No module named '_cffi_backend'

**Comment by ricko2991** [comment]
Try this:
pip3 install flask
pip3 install Flask_Bcrypt

**Comment by jamesmiller9048** [comment]
yes I installed both still error is shown

**Comment by ricko2991** [comment]
pip3 install cffi

**Comment by jamesmiller9048** [comment]
Stop fooling around

**Comment by Enel778** [comment]
I am not kidding. I've tried to get it right, If you're really pissed off, read and study the code, and find someone else who has solved it. 

you do not respect the people who have helped you 👎

**Comment by tuzoceh** [comment]
Hi all,newbie to all this,got to install kali on my windows machine but it won't install GUI,any ideas?

**Comment by malwaredllc** [comment]
Look at the Wiki for FAQ or use the Discord support server to get help. Please only submit issues for bugs.
