### ISSUE TITLE
Windows payload execution error WinError 10061

### ISSUE THREAD

**Issue by ultimategamer309** [malwaredllc/byob#331]
When ever I run the windows exe payload o victim computer a terminal opens then has errors and closes. The victims computer is never added to the bots. When the exe is ran from cmd with --debug the out out is:
```
Traceback (most recent call last):
  File "urllib\request.py", line 1319, in do_open
  File "http\client.py", line 1230, in request
  File "http\client.py", line 1276, in _send_request
  File "http\client.py", line 1225, in endheaders
  File "http\client.py", line 1004, in _send_output
  File "http\client.py", line 944, in send
  File "http\client.py", line 915, in connect
  File "socket.py", line 808, in create_connection
  File "socket.py", line 796, in create_connection
ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "byob_n4g.py", line 5, in <module>
  File "<string>", line 1, in <module>
  File "urllib\request.py", line 222, in urlopen
  File "urllib\request.py", line 525, in open
  File "urllib\request.py", line 542, in _open
  File "urllib\request.py", line 502, in _call_chain
  File "urllib\request.py", line 1348, in http_open
  File "urllib\request.py", line 1322, in do_open
urllib.error.URLError: <urlopen error [WinError 10061] No connection could be made because the target machine actively refused it>
[8520] Failed to execute script byob_n4g
```

The exact same thing happens with the python payload and on linux mint.

**Comment by fireFerry** [comment]
Have you port forwarded?

**Comment by ultimategamer309** [comment]
> Have you port forwarded?

I do not think so

**Comment by fireFerry** [comment]
Please do that first, ports 1337-1339, for more help please join the Discord server, we're happy to support you there!
