### ISSUE TITLE
TypeError: can't apply this __setattr__ to DefaultMeta object (web-gui)

### ISSUE THREAD

**Issue by RealKevinApetrei** [malwaredllc/byob#341]
When running `run.py` after running `startup.sh` on Kali Linux and having Python3.8.4 installed.

I keep getting this error:

```
Traceback (most recent call last):
  File "run.py", line 1, in <module>
    from buildyourownbotnet import app
  File "/home/pc-02/byob/web-gui/buildyourownbotnet/__init__.py", line 18, in <module>
    db = SQLAlchemy(app)
  File "/usr/lib/python3/dist-packages/flask_sqlalchemy/__init__.py", line 716, in __init__
    self.Model = self.make_declarative_base(model_class, metadata)
  File "/usr/lib/python3/dist-packages/flask_sqlalchemy/__init__.py", line 798, in make_declarative_base
    model.query_class = self.Query
  File "/usr/lib/python3/dist-packages/sqlalchemy/ext/declarative/api.py", line 79, in __setattr__
    _add_attribute(cls, key, value)
  File "/usr/lib/python3/dist-packages/sqlalchemy/ext/declarative/base.py", line 802, in _add_attribute
    type.__setattr__(cls, key, value)
TypeError: can't apply this __setattr__ to DefaultMeta object
```

**Comment by malwaredllc** [comment]
Use Python 3.7, later versions are not yet supported.
