### ISSUE TITLE
Building wheel for numpy (setup.py)...

### ISSUE THREAD

**Issue by gsqsimjaa** [malwaredllc/byob#379]
When trying to install the requirements or the startup.sh after a time it shows:

`Requirement already satisfied: certifi>=2017.4.17 in /usr/lib/python3/dist-packages (from requests==2.20.0->-r requirements.txt (line 15)) (2020.4.5.1)
Building wheels for collected packages: numpy, pyxhook, pycryptodomex, py-cryptonight, pyrx
  Building wheel for numpy (setup.py) ... -
`
The "-" in the end is spinning, so its loading. But it does not come to an end. I have waited for 2 hours, but it did not work. Uninstalled and reinstalled numpy. Im using Ubuntu 20.10 on an ssh, but its the same on other ubuntu versions. If I install Raspberry OS, I do not have this issue, but another when building the payload (already opened another issue a few weeks ago). 

thank you for your help.

Edit: After a long time installing it tried to install the other stuff: But there are some other fails, too:
`Building wheel for numpy (setup.py) ... done
  Created wheel for numpy: filename=numpy-1.15.2-cp38-cp38-linux_aarch64.whl size=12104181 sha256=1882d95b7c97b6697b68793f7add98fc614f2388007546cb9b93b00e68ee0eab
  Stored in directory: /home/ubuntu/.cache/pip/wheels/1a/3e/21/18e41365c30013ab2440919972a489bbd68d44ed16772cbf39
  Building wheel for pyxhook (setup.py) ... done
  Created wheel for pyxhook: filename=pyxhook-1.0.0-py3-none-any.whl size=4754 sha256=35f175ea8475214cf253b0289c04460e86b6fbfc0b566b395ff1e846f8f60b41
  Stored in directory: /home/ubuntu/.cache/pip/wheels/9b/2d/b5/f207c6240de6a02937a430250e641975293d1e14b858d11280
  Building wheel for pycryptodomex (setup.py) ... done
  Created wheel for pycryptodomex: filename=pycryptodomex-3.8.1-cp38-cp38-linux_aarch64.whl size=9639909 sha256=785fdddc98b4e6ec9aa3b73c1844589fe26262820ab03e43a1973cb1916da596
  Stored in directory: /home/ubuntu/.cache/pip/wheels/39/be/27/d91b06e155d053d94b34924334ced91ac0cd0e3067580358bb
  Building wheel for py-cryptonight (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-9i4021ke/py-cryptonight/setup.py'"'"'; __file__='"'"'/tmp/pip-install-9i4021ke/py-cryptonight/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-vf2j6oj2
       cwd: /tmp/pip-install-9i4021ke/py-cryptonight/
  Complete output (32 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-aarch64-3.8
  creating build/lib.linux-aarch64-3.8/pycryptonight
  copying pycryptonight/__init__.py -> build/lib.linux-aarch64-3.8/pycryptonight
  creating build/lib.linux-aarch64-3.8/pycryptonight/tests
  copying pycryptonight/tests/__init__.py -> build/lib.linux-aarch64-3.8/pycryptonight/tests
  copying pycryptonight/tests/test.py -> build/lib.linux-aarch64-3.8/pycryptonight/tests
  running egg_info
  writing py_cryptonight.egg-info/PKG-INFO
  writing dependency_links to py_cryptonight.egg-info/dependency_links.txt
  writing requirements to py_cryptonight.egg-info/requires.txt
  writing top-level names to py_cryptonight.egg-info/top_level.txt
  reading manifest file 'py_cryptonight.egg-info/SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  writing manifest file 'py_cryptonight.egg-info/SOURCES.txt'
  creating build/lib.linux-aarch64-3.8/pycryptonight/tests/data
  copying pycryptonight/tests/data/tests-fast.txt -> build/lib.linux-aarch64-3.8/pycryptonight/tests/data
  copying pycryptonight/tests/data/tests-slow-1.txt -> build/lib.linux-aarch64-3.8/pycryptonight/tests/data
  copying pycryptonight/tests/data/tests-slow-2.txt -> build/lib.linux-aarch64-3.8/pycryptonight/tests/data
  copying pycryptonight/tests/data/tests-slow-4.txt -> build/lib.linux-aarch64-3.8/pycryptonight/tests/data
  copying pycryptonight/tests/data/tests-slow.txt -> build/lib.linux-aarch64-3.8/pycryptonight/tests/data
  running build_ext
  building '_pycryptonight' extension
  creating build/temp.linux-aarch64-3.8
  creating build/temp.linux-aarch64-3.8/src
  creating build/temp.linux-aarch64-3.8/src/cryptonight
  aarch64-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -DNO_JIT=1 -I. -Isrc/ -Isrc/cryptonight -I/usr/include/python3.8 -c src/cryptonight/aesb.c -o build/temp.linux-aarch64-3.8/src/cryptonight/aesb.o -std=gnu11 -maes
  aarch64-linux-gnu-gcc: error: unrecognized command-line option ‘-maes’
  error: command 'aarch64-linux-gnu-gcc' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for py-cryptonight
  Running setup.py clean for py-cryptonight
  Building wheel for pyrx (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-9i4021ke/pyrx/setup.py'"'"'; __file__='"'"'/tmp/pip-install-9i4021ke/pyrx/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-up6by0o_
       cwd: /tmp/pip-install-9i4021ke/pyrx/
  Complete output (45 lines):
  running bdist_wheel
  running build
  running build_ext
  Traceback (most recent call last):
    File "/tmp/pip-install-9i4021ke/pyrx/setup.py", line 21, in run
      out = subprocess.check_output(['cmake', '--version'])
    File "/usr/lib/python3.8/subprocess.py", line 411, in check_output
      return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
    File "/usr/lib/python3.8/subprocess.py", line 489, in run
      with Popen(*popenargs, kwargs) as process:
    File "/usr/lib/python3.8/subprocess.py", line 854, in __init__
      self._execute_child(args, executable, preexec_fn, close_fds,
    File "/usr/lib/python3.8/subprocess.py", line 1702, in _execute_child
      raise child_exception_type(errno_num, err_msg, err_filename)
  FileNotFoundError: [Errno 2] No such file or directory: 'cmake'
  
  During handling of the above exception, another exception occurred:
  
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-9i4021ke/pyrx/setup.py", line 59, in <module>
      setup(
    File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 163, in setup
      return distutils.core.setup(attrs)
    File "/usr/lib/python3.8/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/usr/lib/python3.8/distutils/dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/usr/lib/python3/dist-packages/wheel/bdist_wheel.py", line 223, in run
      self.run_command('build')
    File "/usr/lib/python3.8/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/usr/lib/python3.8/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/usr/lib/python3.8/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/tmp/pip-install-9i4021ke/pyrx/setup.py", line 23, in run
      raise RuntimeError("CMake must be installed to build the following extensions: " +
  RuntimeError: CMake must be installed to build the following extensions: pyrx
  ----------------------------------------
  ERROR: Failed building wheel for pyrx
  Running setup.py clean for pyrx
Successfully built numpy pyxhook pycryptodomex
Failed to build py-cryptonight pyrx
ERROR: opencv-python 4.5.1.48 has requirement numpy>=1.19.3, but you'll have numpy 1.15.2 which is incompatible.
Installing collected packages: cachelib, flask-session, wtforms, flask-wtf, SQLAlchemy, Flask-SQLAlchemy, Flask-Login, Flask-Bcrypt, flask-mail, mss, WMI, numpy, python-xlib, pyxhook, urllib3, idna, requests, twilio, colorama, pycryptodomex, py-cryptonight, pyrx, opencv-python
    Running setup.py install for py-cryptonight ... error
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-9i4021ke/py-cryptonight/setup.py'"'"'; __file__='"'"'/tmp/pip-install-9i4021ke/py-cryptonight/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-z3z9yidm/install-record.txt --single-version-externally-managed --user --prefix= --compile --install-headers /home/ubuntu/.local/include/python3.8/py-cryptonight
         cwd: /tmp/pip-install-9i4021ke/py-cryptonight/
    Complete output (32 lines):
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-aarch64-3.8
    creating build/lib.linux-aarch64-3.8/pycryptonight
    copying pycryptonight/__init__.py -> build/lib.linux-aarch64-3.8/pycryptonight
    creating build/lib.linux-aarch64-3.8/pycryptonight/tests
    copying pycryptonight/tests/__init__.py -> build/lib.linux-aarch64-3.8/pycryptonight/tests
    copying pycryptonight/tests/test.py -> build/lib.linux-aarch64-3.8/pycryptonight/tests
    running egg_info
    writing py_cryptonight.egg-info/PKG-INFO
    writing dependency_links to py_cryptonight.egg-info/dependency_links.txt
    writing requirements to py_cryptonight.egg-info/requires.txt
    writing top-level names to py_cryptonight.egg-info/top_level.txt
    reading manifest file 'py_cryptonight.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    writing manifest file 'py_cryptonight.egg-info/SOURCES.txt'
    creating build/lib.linux-aarch64-3.8/pycryptonight/tests/data
    copying pycryptonight/tests/data/tests-fast.txt -> build/lib.linux-aarch64-3.8/pycryptonight/tests/data
    copying pycryptonight/tests/data/tests-slow-1.txt -> build/lib.linux-aarch64-3.8/pycryptonight/tests/data
    copying pycryptonight/tests/data/tests-slow-2.txt -> build/lib.linux-aarch64-3.8/pycryptonight/tests/data
    copying pycryptonight/tests/data/tests-slow-4.txt -> build/lib.linux-aarch64-3.8/pycryptonight/tests/data
    copying pycryptonight/tests/data/tests-slow.txt -> build/lib.linux-aarch64-3.8/pycryptonight/tests/data
    running build_ext
    building '_pycryptonight' extension
    creating build/temp.linux-aarch64-3.8
    creating build/temp.linux-aarch64-3.8/src
    creating build/temp.linux-aarch64-3.8/src/cryptonight
    aarch64-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -DNO_JIT=1 -I. -Isrc/ -Isrc/cryptonight -I/usr/include/python3.8 -c src/cryptonight/aesb.c -o build/temp.linux-aarch64-3.8/src/cryptonight/aesb.o -std=gnu11 -maes
    aarch64-linux-gnu-gcc: error: unrecognized command-line option ‘-maes’
    error: command 'aarch64-linux-gnu-gcc' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-9i4021ke/py-cryptonight/setup.py'"'"'; __file__='"'"'/tmp/pip-install-9i4021ke/py-cryptonight/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-z3z9yidm/install-record.txt --single-version-externally-managed --user --prefix= --compile --install-headers /home/ubuntu/.local/include/python3.8/py-cryptonight Check the logs for full command output.
ubuntu@ubuntu:~/byob/web-gui$ 
`

**Comment by gsqsimjaa** [comment]
just tried it again a few times, eventually it worked
