### ISSUE TITLE
Windows Payloads not working

### ISSUE THREAD

**Issue by neviosng** [malwaredllc/byob#470]
When I´ll use the Executable Format for a new Payload, it doesn´t work. For Python, it´s everything okay.

**Comment by fireFerry** [comment]
Is there any error? Could you elaborate?

**Comment by SentinalMax** [comment]
> Is there any error? Could you elaborate?

Generating python payloads works well. But when I generate windows payloads and select the 32bit architecture (only option) I get an "Oops! you broke something... (500)" Would you like me to show you my shell?

**Comment by fireFerry** [comment]
Yes, that would be nicie

**Comment by SentinalMax** [comment]
> Yes, that would be nice

I figured out that docker.io wasn't installed properly on my end... but now when I try and create a winx32 payload my shell keeps echoing b' ' and never finishes creating the payload.

**Comment by fireFerry** [comment]
If you installed docker with `sudo apt install docker.io` then that's an outdated method of installing docker and won't work with byob. You'll need to install docker from [the official docker docs](https://docs.docker.com/engine/install/) and then run startup.sh again.

**Comment by TormentedSoul666** [comment]
Also don't forget to add your user to the docker group.

**Comment by windowshopr** [comment]
I get the same error. Windows 10, Python 3.7. I installed docker, ran the startup.sh, and with docker running, launched the web app, created an account, then tried to create a Windows executable payload. This is the traceback I get:

```
ERROR:buildyourownbotnet:Exception on /api/payload/generate [POST]
Traceback (most recent call last):
  File "C:\Users\...\AppData\Roaming\Python\Python37\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\...\AppData\Roaming\Python\Python37\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\...\AppData\Roaming\Python\Python37\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\...\AppData\Roaming\Python\Python37\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\...\AppData\Roaming\Python\Python37\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\...\AppData\Roaming\Python\Python37\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\...\AppData\Roaming\Python\Python37\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\...\OneDrive\Desktop\Python_Scripts\SQL_Injection_and_Hacking\byob\web-gui\buildyourownbotnet\api\payload\routes.py", line 37, in payload_generate
    if freeze and subprocess.check_call(['which','docker']) != 0:
  File "C:\Users\...\AppData\Roaming\Python\Python37\lib\subprocess.py", line 358, in check_call
    retcode = call(*popenargs, **kwargs)
  File "C:\Users\...\AppData\Roaming\Python\Python37\lib\subprocess.py", line 339, in call
    with Popen(*popenargs, **kwargs) as p:
  File "C:\Users\...\AppData\Roaming\Python\Python37\lib\subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "C:\Users\...\AppData\Roaming\Python\Python37\lib\subprocess.py", line 1207, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified
```

**Comment by fireFerry** [comment]
Byob web-gui is Linux only.

**Comment by windowshopr** [comment]
Ah, well hopefully Windows will be included in the future. Thanks!

**Comment by windowshopr** [comment]
This feature also doesn’t work on Kali Linux. 2021.3. Just tried to create a Windows x32 executable payload, same error. Also wonder if x64 is necessary in the future. Would be nice to see this working, this issue should be re-opened ?

**Comment by windowshopr** [comment]
To elaborate, getting the same error as in #380
