### ISSUE TITLE
BYOB Web-Gui not working on Windows

### ISSUE THREAD

**Issue by RithvikGogineni** [malwaredllc/byob#499]
Hi, I am trying to run byob web-GUI but it is giving me a strange error:
Traceback (most recent call last):
  File "run.py", line 1, in <module>
    from buildyourownbotnet import create_app
  File "/mnt/c/Users/Rithv/Downloads/byob/web-gui/buildyourownbotnet/__init__.py", line 18, in <module>
    c2 = server.C2(debug=_debug)
  File "/mnt/c/Users/Rithv/Downloads/byob/web-gui/buildyourownbotnet/server.py", line 68, in __init__
    self.socket = self._init_socket(self.port)
  File "/mnt/c/Users/Rithv/Downloads/byob/web-gui/buildyourownbotnet/server.py", line 123, in _init_socket
    s.bind(('0.0.0.0', port))
PermissionError: [Errno 13] Permission denied
It would be great if you could help. 
I am using ubuntu subsystem in windows 10

**Comment by fireFerry** [comment]
BYOB web-gui is Linux only. Using WSL isn't supported, you need to use a vm, bare metal, dualboot, etc.
