### ISSUE TITLE
Run web GUI in Docker container...

### ISSUE THREAD

**Issue by fsociety3765** [malwaredllc/byob#504]
Hi all,

Are the docs in the wiki on running the web GUI in a Docker container up to date and still relevant? 

I am trying to accomplish this so I can run the web GUI as a service in the background rather than in the foreground. 

I have tried using the `git clone` method as shown in the `Dockerfile` and also the advised alternative, remove the `git clone` part. I had to add an `ADD` statement to the file to copy the contents of the web-gui directory into the image when not using `git clone`.

`Dockefile` below...

```
FROM ubuntu:bionic

WORKDIR /app
RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y build-essential cmake && \
    apt-get install -y python3.6 python3-pip

ADD ./web-gui/ /app/web-gui/

WORKDIR /app/web-gui
RUN python3.6 -m pip install pip --upgrade && \
    python3.6 -m pip install -r requirements.txt && \
    rm -rf .gitignore .travis.yml README.md requirements.txt startup.sh docker-pyinstaller*

EXPOSE 5000 1337 1338 1339
ENTRYPOINT ["python3.6", "run.py"]
```

I placed this file in the root of the web-gui directory of the repo and ran the build. The build completed but the container exits with an error code quickly after starting...

```
2021-09-16T02:29:27.148763320Z Traceback (most recent call last):
2021-09-16T02:29:27.148819346Z   File "/usr/lib/python3.6/urllib/request.py", line 1325, in do_open
2021-09-16T02:29:27.148832356Z     encode_chunked=req.has_header('Transfer-encoding'))
2021-09-16T02:29:27.148837185Z   File "/usr/lib/python3.6/http/client.py", line 1281, in request
2021-09-16T02:29:27.148841848Z     self._send_request(method, url, body, headers, encode_chunked)
2021-09-16T02:29:27.148858755Z   File "/usr/lib/python3.6/http/client.py", line 1327, in _send_request
2021-09-16T02:29:27.148863746Z     self.endheaders(body, encode_chunked=encode_chunked)
2021-09-16T02:29:27.148868356Z   File "/usr/lib/python3.6/http/client.py", line 1276, in endheaders
2021-09-16T02:29:27.148872996Z     self._send_output(message_body, encode_chunked=encode_chunked)
2021-09-16T02:29:27.148881355Z   File "/usr/lib/python3.6/http/client.py", line 1042, in _send_output
2021-09-16T02:29:27.148885922Z     self.send(msg)
2021-09-16T02:29:27.148890381Z   File "/usr/lib/python3.6/http/client.py", line 980, in send
2021-09-16T02:29:27.148894911Z     self.connect()
2021-09-16T02:29:27.148899422Z   File "/usr/lib/python3.6/http/client.py", line 952, in connect
2021-09-16T02:29:27.148903924Z     (self.host,self.port), self.timeout, self.source_address)
2021-09-16T02:29:27.148908437Z   File "/usr/lib/python3.6/socket.py", line 724, in create_connection
2021-09-16T02:29:27.148913032Z     raise err
2021-09-16T02:29:27.148917488Z   File "/usr/lib/python3.6/socket.py", line 713, in create_connection
2021-09-16T02:29:27.148931087Z     sock.connect(sa)
2021-09-16T02:29:27.148935734Z OSError: [Errno 99] Cannot assign requested address
2021-09-16T02:29:27.148940265Z 
2021-09-16T02:29:27.148944684Z During handling of the above exception, another exception occurred:
2021-09-16T02:29:27.148949049Z 
2021-09-16T02:29:27.148953308Z Traceback (most recent call last):
2021-09-16T02:29:27.148957642Z   File "run.py", line 1, in <module>
2021-09-16T02:29:27.148962410Z     from buildyourownbotnet import create_app
2021-09-16T02:29:27.148966795Z   File "/app/web-gui/buildyourownbotnet/__init__.py", line 16, in <module>
2021-09-16T02:29:27.148971459Z     from buildyourownbotnet import client, server
2021-09-16T02:29:27.148975775Z   File "/app/web-gui/buildyourownbotnet/client.py", line 122, in <module>
2021-09-16T02:29:27.148980296Z     C2_HOST = util.public_ip()
2021-09-16T02:29:27.148984659Z   File "/app/web-gui/buildyourownbotnet/core/util.py", line 84, in public_ip
2021-09-16T02:29:27.148989148Z     return urlopen('http://api.ipify.org').read().decode()
2021-09-16T02:29:27.149013914Z   File "/usr/lib/python3.6/urllib/request.py", line 223, in urlopen
2021-09-16T02:29:27.149018482Z     return opener.open(url, data, timeout)
2021-09-16T02:29:27.149022454Z   File "/usr/lib/python3.6/urllib/request.py", line 526, in open
2021-09-16T02:29:27.149026544Z     response = self._open(req, data)
2021-09-16T02:29:27.149030436Z   File "/usr/lib/python3.6/urllib/request.py", line 544, in _open
2021-09-16T02:29:27.149034518Z     '_open', req)
2021-09-16T02:29:27.149038386Z   File "/usr/lib/python3.6/urllib/request.py", line 504, in _call_chain
2021-09-16T02:29:27.149042452Z     result = func(*args)
2021-09-16T02:29:27.149047010Z   File "/usr/lib/python3.6/urllib/request.py", line 1353, in http_open
2021-09-16T02:29:27.149051200Z     return self.do_open(http.client.HTTPConnection, req)
2021-09-16T02:29:27.149055229Z   File "/usr/lib/python3.6/urllib/request.py", line 1327, in do_open
2021-09-16T02:29:27.149500184Z     raise URLError(err)
2021-09-16T02:29:27.149850626Z urllib.error.URLError: <urlopen error [Errno 99] Cannot assign requested address>
```

**Comment by fiki574** [comment]
Hey. I've done this on my Ubuntu 16.04 LTS server, and worked fine so posted it in the Wiki. Those pages are by no means official as I've done them myself, and not the official devs.

Have in mind that once you do get the BYOB Web GUI running in a Docker container, most parts of the site with payload generation and such features will not be working as the Docker itself is being used to generate precompiled payloads, which would require you to do a "Docker in Docker" sort of thing, which I gave up on since it went above and beyond my then-understanding. Best bet is to install it as a file system binary/app.
