### ISSUE TITLE
socket error

### ISSUE THREAD

**Issue by isithacker** [malwaredllc/byob#552]
it gives me a python error when I execute run.py
im using Ubuntu LTS 20.04 and python 3.9

here is the error that it gave me

Traceback (most recent call last):
  File "/usr/lib/python3.9/urllib/request.py", line 1346, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/usr/lib/python3.9/http/client.py", line 1285, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.9/http/client.py", line 1331, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.9/http/client.py", line 1280, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.9/http/client.py", line 1040, in _send_output
    self.send(msg)
  File "/usr/lib/python3.9/http/client.py", line 980, in send
    self.connect()
  File "/usr/lib/python3.9/http/client.py", line 946, in connect
    self.sock = self._create_connection(
  File "/usr/lib/python3.9/socket.py", line 823, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "/usr/lib/python3.9/socket.py", line 954, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kali/byob/web-gui/run.py", line 1, in <module>
    from buildyourownbotnet import create_app
  File "/home/kali/byob/web-gui/buildyourownbotnet/__init__.py", line 16, in <module>
    from buildyourownbotnet import client, server
  File "/home/kali/byob/web-gui/buildyourownbotnet/client.py", line 122, in <module>
    C2_HOST = util.public_ip()
  File "/home/kali/byob/web-gui/buildyourownbotnet/core/util.py", line 84, in public_ip
    return urlopen('http://api.ipify.org').read().decode()
  File "/usr/lib/python3.9/urllib/request.py", line 214, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.9/urllib/request.py", line 517, in open
    response = self._open(req, data)
  File "/usr/lib/python3.9/urllib/request.py", line 534, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/usr/lib/python3.9/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.9/urllib/request.py", line 1375, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/usr/lib/python3.9/urllib/request.py", line 1349, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno -3] Temporary failure in name resolution>

it seems like a network error, is it?

**Comment by malwaredllc** [comment]
Looks like your VM network is configured incorrectly most likely. Go to the Discord (link in README) for help troubleshooting this
