### ISSUE TITLE
unable to locate directory containing user-installed packages

### ISSUE THREAD

**Issue by abdalmajid77** [malwaredllc/byob#587]
![image](https://user-images.githubusercontent.com/53356214/170891187-70391d41-ada4-4f18-96cd-10427897669f.png)

**Comment by onefive1156** [comment]
me too

**Comment by trewqqwert** [comment]
I encountered the same issue. 

After modifying 
https://github.com/malwaredllc/byob/blob/24b81360fc8e831f25dd5304d2327ba7a30d2bb3/web-gui/buildyourownbotnet/server.py#L90
to
```
site_packages = [os.path.abspath(_) for _ in sys.path if os.path.isdir(_)]
```
the script is able to proceed.

**Comment by devdaskumar** [comment]
@trewqqwert 
![Screenshot_2022-06-02_20-46-24](https://user-images.githubusercontent.com/73071736/171662906-510b247c-cfb9-4d97-b0be-9dc875d19523.png)


after modifing  give this error

**Comment by Amdubaloch** [comment]
> ![image](https://user-images.githubusercontent.com/53356214/170891187-70391d41-ada4-4f18-96cd-10427897669f.png)

How to solve this issue_

**Comment by xCrAshInSiDex** [comment]
Same issues here, tried on Debian 11, Debian 8, Arch Linux (Garuda + Black Arch) and Centos 7, same issue everywhere...

**Comment by Rayhamen101** [comment]
unable to locate directory containing user-installed packages. Same error as well and surf the web for a solution but nothing yet.

**Comment by Vector1199** [comment]
![Screenshot from 2022-08-04 20-36-42](https://user-images.githubusercontent.com/30725702/182881827-42e7e437-890b-4f5b-ac2d-fb5360790b26.png)


I found same errors on manjaro Linux I also tried on ubuntu and kali as well but the same error I installed most requirement tools manually but still, an error was the

**Comment by DeividReinkeSchiitz** [comment]
> ![Screenshot from 2022-08-04 20-36-42](https://user-images.githubusercontent.com/30725702/182881827-42e7e437-890b-4f5b-ac2d-fb5360790b26.png)
> 
> I found same errors on manjaro Linux I also tried on ubuntu and kali as well but the same error I installed most requirement tools manually but still, an error was the

I have the same problem in kali. Try to update the numpy library to the last version. I used the 1.23.2.


**First install the other dependencies**
```
pip3 install Werkzeug==2.0.0 SQLAlchemy==1.3.23 flask flask_session flask_wtf Flask_SQLAlchemy Flask_Login Flask_Bcrypt flask_mail wtforms mss==3.3.0 WMI==1.4.9 pyxhook==1.0.0 twilio==6.14.0 colorama==0.3.9 requests==2.20.0 pycryptodomex==3.8.1 py-cryptonight>=0.2.4 opencv-python;python_version>'3' pypiwin32==223;sys.platform=='win32' pyHook==1.5.1;sys.platform=='win32'
```
**And last numpy version**
```
pip3 install numpy
```

**Comment by Feliperdg** [comment]
estou com mesmo problema, alguem conseguir resolver ?  

unable to locate directory containing user-installed packages byob

**Comment by SuliiiP** [comment]
fixed it by pip3 install -U Flask

**Comment by SHADOW-SCRIPT** [comment]
> 

@DeividReinkeSchiitz that code doesn't work in kali? isn't that just for Windows?

**Comment by DeividReinkeSchiitz** [comment]
@SHADOW-SCRIPT the byob works well in kali for me, i think that the problem occurs because of some packages conflicts between the versions of each other, this things happen a lot in languages that have package manager. If you are having issues try to open the requirements and install each version manually and see the output. It will probably tell you what package you installed who needs to be updated.

**Comment by Shi57** [comment]
> I encountered the same issue.
> 
> After modifying
> 
> https://github.com/malwaredllc/byob/blob/24b81360fc8e831f25dd5304d2327ba7a30d2bb3/web-gui/buildyourownbotnet/server.py#L90
> 
> to
> 
> ```
> site_packages = [os.path.abspath(_) for _ in sys.path if os.path.isdir(_)]
> ```
> 
> the script is able to proceed.

It's Work For Me, Thanks

**Comment by Hacker1718** [comment]
has anyone fixed the issue yet of Unable to locate.................

**Comment by Hacker1718** [comment]
I fixed it

**Comment by tonykcmarsh** [comment]
ive tried everything here no good

**Comment by EndermanOnek** [comment]
#

> I encountered the same issue.
> 
> After modifying
> 
> https://github.com/malwaredllc/byob/blob/24b81360fc8e831f25dd5304d2327ba7a30d2bb3/web-gui/buildyourownbotnet/server.py#L90
> 
> 
> to
> ```
> site_packages = [os.path.abspath(_) for _ in sys.path if os.path.isdir(_)]
> ```
> 
> the script is able to proceed.

Worked for me

**Comment by Zetrix01** [comment]
@trewqqwert  i love u , it worked

**Comment by Agent246** [comment]
> I encountered the same issue.
> 
> After modifying
> 
> https://github.com/malwaredllc/byob/blob/24b81360fc8e831f25dd5304d2327ba7a30d2bb3/web-gui/buildyourownbotnet/server.py#L90
> 
> 
> to
> ```
> site_packages = [os.path.abspath(_) for _ in sys.path if os.path.isdir(_)]
> ```
> 
> the script is able to proceed.

THANK YOUUUUUUUUUUU VERY MUCHHHH. I was trying to solve this problem for weeks and you solved it for me THANKUUUUUUUUUUUUUU!!!!

**Comment by Stop423** [comment]
> I encountered the same issue.
> 
> After modifying
> 
> https://github.com/malwaredllc/byob/blob/24b81360fc8e831f25dd5304d2327ba7a30d2bb3/web-gui/buildyourownbotnet/server.py#L90
> 
> to
> 
> ```
> site_packages = [os.path.abspath(_) for _ in sys.path if os.path.isdir(_)]
> ```
> 
> the script is able to proceed.

Thank you so much

**Comment by Estebob1234** [comment]
how do i modify the script someone pls help im new to kali linux i just dont know how to modify it. it gives me the this document is a read only text and i cant save it.

**Comment by Teflotask** [comment]
@Estebob1234 learn basic navigation for linux and use nano <file name> 
nano is the editor just like notepad++ , it will open the file and you can edit

**Comment by script-hunter** [comment]
> I encountered the same issue.
> 
> After modifying
> 
> https://github.com/malwaredllc/byob/blob/24b81360fc8e831f25dd5304d2327ba7a30d2bb3/web-gui/buildyourownbotnet/server.py#L90
> 
> 
> to
> ```
> site_packages = [os.path.abspath(_) for _ in sys.path if os.path.isdir(_)]
> ```
> 
> the script is able to proceed.

it worked for me <3 THANKS

**Comment by Teflotask** [comment]
> > I encountered the same issue.
> > After modifying
> > https://github.com/malwaredllc/byob/blob/24b81360fc8e831f25dd5304d2327ba7a30d2bb3/web-gui/buildyourownbotnet/server.py#L90
> > 
> > to
> > ```
> > site_packages = [os.path.abspath(_) for _ in sys.path if os.path.isdir(_)]
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > the script is able to proceed.
> 
> It's Work For Me, Thanks

This worked for me .

**Comment by sneakylizard123-4** [comment]
now i get this error:
┌──(venv)─(user㉿localhost)-[~/byob/web-gui]
└─$ python3 run.py       
Traceback (most recent call last):
  File "/home/sneak/byob/web-gui/run.py", line 1, in <module>
    from buildyourownbotnet import create_app
  File "/home/sneak/byob/web-gui/buildyourownbotnet/__init__.py", line 16, in <module>
    from buildyourownbotnet import client, server
  File "/home/sneak/byob/web-gui/buildyourownbotnet/server.py", line 20, in <module>
    import requests
  File "/home/sneak/byob/web-gui/venv/lib/python3.13/site-packages/requests/__init__.py", line 43, in <module>
    import urllib3
  File "/home/sneak/byob/web-gui/venv/lib/python3.13/site-packages/urllib3/__init__.py", line 8, in <module>
    from .connectionpool import (
    ...<3 lines>...
    )
  File "/home/sneak/byob/web-gui/venv/lib/python3.13/site-packages/urllib3/connectionpool.py", line 11, in <module>
    from .exceptions import (
    ...<13 lines>...
    )
  File "/home/sneak/byob/web-gui/venv/lib/python3.13/site-packages/urllib3/exceptions.py", line 2, in <module>
    from .packages.six.moves.http_client import (
        IncompleteRead as httplib_IncompleteRead
    )
ModuleNotFoundError: No module named 'urllib3.packages.six.moves'
