### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'unbound_message'

### ISSUE THREAD

**Issue by sithortodox** [malwaredllc/byob#607]
I run python3 run.py I get this error

**Comment by sithortodox** [comment]
Traceback (most recent call last):
  File "run.py", line 1, in <module>
    from buildyourownbotnet import create_app
  File "/root/byob/web-gui/buildyourownbotnet/__init__.py", line 2, in <module>
    from flask import Flask
  File "/usr/local/lib/python3.8/dist-packages/flask/__init__.py", line 4, in <module>
    from . import json as json
  File "/usr/local/lib/python3.8/dist-packages/flask/json/__init__.py", line 8, in <module>
    from ..globals import current_app
  File "/usr/local/lib/python3.8/dist-packages/flask/globals.py", line 56, in <module>
    app_ctx: "AppContext" = LocalProxy(  # type: ignore[assignment]
TypeError: __init__() got an unexpected keyword argument 'unbound_message'

**Comment by Catchii** [comment]
same issue

**Comment by C1oover** [comment]
bump, same here fresh install on ubuntu server.

**Comment by C1oover** [comment]
Duplicate of #604

**Comment by Zaeem20** [comment]
@sithortodox can you please mention your python version,

just type this:
```pip3 install flask==2.2.2  flask-sqlalchemy==3.0.2```

this issue is probably with werkzeug version.
by doing this i fixed it
