### ISSUE TITLE
ModuleNotFoundError: No module named 'flask_bcrypt'

### ISSUE THREAD

**Issue by Ram001-code** [malwaredllc/byob#617]
I tried to run the file run.py inside the web-gui folder but it's giving this error

Traceback (most recent call last):
  File "/home/ram/byob/web-gui/run.py", line 1, in <module>
    from buildyourownbotnet import create_app
  File "/home/ram/byob/web-gui/buildyourownbotnet/__init__.py", line 16, in <module>
    from buildyourownbotnet import client, server
  File "/home/ram/byob/web-gui/buildyourownbotnet/server.py", line 32, in <module>
    from .models import db
  File "/home/ram/byob/web-gui/buildyourownbotnet/models.py", line 2, in <module>
    from flask_bcrypt import Bcrypt
ModuleNotFoundError: No module named 'flask_bcrypt'

**Comment by Karalojko** [comment]
Install the requirements.txt

**Comment by fork-ina-socket** [comment]
just try installing it with pip??`pip3 install flask_bycrypt`

**Comment by Ousellekke** [comment]
> Install the requirements.txt

command for that?
