### ISSUE TITLE
Not Starting Web-gui

### ISSUE THREAD

**Issue by Swe-HimelRana** [malwaredllc/byob#620]
**Error: TypeError: __init__() got an unexpected keyword argument 'unbound_message'**

I am using Ubuntu Server 20.04 LTS

I have completed installing `requirements.txt` packages and also installed all other packages by sudo` ./startup.sh`
Also, **docker.io** is running on my server

```
To use some Byob features, you must reboot your system. If this is not your first time running this script, please answer no. Reboot now? [Y/n]: n
Running C2 server with locally hosted web app GUI...
Navigate to http://127.0.0.1:5000 and set up your user to get started.
Traceback (most recent call last):
  File "run.py", line 1, in <module>
    from buildyourownbotnet import create_app
  File "/root/botnet/byob/web-gui/buildyourownbotnet/__init__.py", line 2, in <module>
    from flask import Flask
  File "/usr/local/lib/python3.8/dist-packages/flask/__init__.py", line 4, in <module>
    from . import json as json
  File "/usr/local/lib/python3.8/dist-packages/flask/json/__init__.py", line 8, in <module>
    from ..globals import current_app
  File "/usr/local/lib/python3.8/dist-packages/flask/globals.py", line 56, in <module>
    app_ctx: "AppContext" = LocalProxy(  # type: ignore[assignment]
TypeError: __init__() got an unexpected keyword argument 'unbound_message'
root@srv:~/botnet/byob/web-gui# pip3 list
```

**Comment by callmecampa** [comment]
Hi,
try this: 

`pip3 install flask==2.2.2 flask-sqlalchemy==3.0.2`

and then run with `python3 run.py`

Let me know

**Comment by MrBanane6969** [comment]
smart
