### ISSUE TITLE
not working 

### ISSUE THREAD

**Issue by cyberpunk20882** [malwaredllc/byob#624]
it is not working can you please fix

**Comment by darkviiolet** [comment]
The run.py doesnt work for me either, it gives a name domain failure:

`Traceback (most recent call last):
  File "/usr/lib/python3.10/urllib/request.py", line 1348, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/usr/lib/python3.10/http/client.py", line 1282, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1328, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1277, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1037, in _send_output
    self.send(msg)
  File "/usr/lib/python3.10/http/client.py", line 975, in send
    self.connect()
  File "/usr/lib/python3.10/http/client.py", line 941, in connect
    self.sock = self._create_connection(
  File "/usr/lib/python3.10/socket.py", line 824, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "/usr/lib/python3.10/socket.py", line 955, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kali/anonima/byob/web-gui/run.py", line 1, in <module>
    from buildyourownbotnet import create_app
  File "/home/kali/anonima/byob/web-gui/buildyourownbotnet/__init__.py", line 16, in <module>
    from buildyourownbotnet import client, server
  File "/home/kali/anonima/byob/web-gui/buildyourownbotnet/client.py", line 122, in <module>
    C2_HOST = util.public_ip()
  File "/home/kali/anonima/byob/web-gui/buildyourownbotnet/core/util.py", line 84, in public_ip
    return urlopen('http://api.ipify.org').read().decode()
  File "/usr/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.10/urllib/request.py", line 519, in open
    response = self._open(req, data)
  File "/usr/lib/python3.10/urllib/request.py", line 536, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/usr/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.10/urllib/request.py", line 1377, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/usr/lib/python3.10/urllib/request.py", line 1351, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno -3] Temporary failure in name resolution>`

in run.py you're importing "create_app" and i cant find it to see if maybe there's smth to fix.

**Comment by kyron500** [comment]
I managed to get this running using Python 3.7.9 on Windows 10 64bit (https://www.python.org/downloads/release/python-379/)
Also, I manually installed PyHook using the whl file:
https://www.lfd.uci.edu/~gohlke/pythonlibs/#pyhook --> pyHook-1.5.1-cp37-cp37m-win_amd64 --> pip install .\pyHook-1.5.1-cp37-cp37m-win_amd64.whl

And I did some changes in the requirements file inside the web-gui folder (requirements.txt):

Werkzeug
SQLAlchemy
flask==2.2
flask_session
flask_wtf
Flask_SQLAlchemy
Flask_Login
Flask_Bcrypt
flask_mail
wtforms
mss==3.3.0
WMI==1.4.9
numpy==1.17.3
pyxhook==1.0.0
twilio==6.14.0
colorama==0.3.9
requests==2.20.0
pycryptodomex==3.8.1
py-cryptonight==0.3.4
opencv-python;python_version>'3'
pypiwin32==223;sys.platform=='win32'
pyHook==1.5.1;sys.platform=='win32'

hopefully it will help you
