### ISSUE TITLE
running the run.py code 

### ISSUE THREAD

**Issue by Glitch-star496** [malwaredllc/byob#641]
Traceback (most recent call last):
  File "/home/kali/byob/web-gui/run.py", line 1, in <module>
    from buildyourownbotnet import create_app
  File "/home/kali/byob/web-gui/buildyourownbotnet/__init__.py", line 2, in <module>
    from flask import Flask
  File "/usr/lib/python3/dist-packages/flask/__init__.py", line 4, in <module>
    from . import json as json
  File "/usr/lib/python3/dist-packages/flask/json/__init__.py", line 8, in <module>
    from ..globals import current_app
  File "/usr/lib/python3/dist-packages/flask/globals.py", line 56, in <module>
    app_ctx: "AppContext" = LocalProxy(  # type: ignore[assignment]
TypeError: LocalProxy.__init__() got an unexpected keyword argument 'unbound_message'

**Comment by Glitch-star496** [comment]
I don't know what to do?

**Comment by Feliperdg** [comment]
tenta instalar flask-bcrypt

**Comment by Poocunt** [comment]
@Feliperdg Is that English or. 

tenta instalar flask-bcrypt

Or do you mean tenta install flask-bcrypt
