### ISSUE TITLE
Absolutely No Idea (Error on sudo ./startup.sh or python3 run.py)

### ISSUE THREAD

**Issue by noahmajors** [malwaredllc/byob#646]
After installing all requirements, including docker, on ubuntu 20.04, and running either ./startup.sh or python3 run.py, I receive the error:

:~/byob/web-gui$ sudo python3 run.py
Traceback (most recent call last):
  File "run.py", line 1, in <module>
    from buildyourownbotnet import create_app
  File "/home/ubuntu/byob/web-gui/buildyourownbotnet/__init__.py", line 2, in <module>
    from flask import Flask
  File "/usr/local/lib/python3.8/dist-packages/flask/__init__.py", line 4, in <module>
    from . import json as json
  File "/usr/local/lib/python3.8/dist-packages/flask/json/__init__.py", line 8, in <module>
    from ..globals import current_app
  File "/usr/local/lib/python3.8/dist-packages/flask/globals.py", line 56, in <module>
    app_ctx: "AppContext" = LocalProxy(  # type: ignore[assignment]
TypeError: __init__() got an unexpected keyword argument 'unbound_message'

**Comment by nullincognito** [comment]
You have to use sudo bash startup.sh
and likewise, login with su (as root)
then use python setup.py after cd /byob

**Comment by noahmajors** [comment]
I did not use the su account, but rather used sudo ./startup.sh since I’m in a linux environment. I’ll take a look into logging in as SuSent from my iPhoneOn Mar 3, 2023, at 1:45 PM, nullincognito ***@***.***> wrote:﻿
You have to use sudo bash startup.sh
and likewise, login with su (as root)
then use python setup.py after cd /byob
