### ISSUE TITLE
problem with __init__.py

### ISSUE THREAD

**Issue by gblancgithub** [malwaredllc/byob#655]
### Please use the Discord Support Server if you need help and reserve creating issues for bug reports.

**Describe the bug**
When running my python progran I get this error:
Traceback (most recent call last):
  File "D:\GB_\gb_OPenAI\whisper-speech2text.py", line 1, in <module>
    import whisper
  File "C:\Users\blanc\AppData\Roaming\Python\Python311\site-packages\whisper.py", line 69, in <module>
    libc = ctypes.CDLL(libc_name)
  File "C:\Program Files\Python311\Lib\ctypes\__init__.py", line 366, in __init__
    if '/' in name or '\\' in name:
TypeError: argument of type 'NoneType' is not iterable

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: windows 11
 - Python version 3.11

**Additional context**

**Comment by gblancgithub** [comment]
Here is the python code of my program ''note: whisper was succesfukky installed):
import whisper

model = whisper.load_model("base")

# load audio and pad/trim it to fit 30 seconds
audio = whisper.load_audio("audio.mp3")
audio = whisper.pad_or_trim(audio)

# make log-Mel spectrogram and move to the same device as the model
mel = whisper.log_mel_spectrogram(audio).to(model.device)

# detect the spoken language
_, probs = model.detect_language(mel)
print(f"Detected language: {max(probs, key=probs.get)}")

# decode the audio
options = whisper.DecodingOptions()
result = whisper.decode(model, mel, options)

# print the recognized text
print(result.text)
