### ISSUE TITLE
No module named 'flask'

### ISSUE THREAD

**Issue by JuJuBunz** [malwaredllc/byob#670]
When running the script run.py on a Ubuntu Virtual Machine I got this error:

Traceback (most recent call last):
  File "/home/jujubunz/byob/web-gui/run.py", line 1, in <module>
    from buildyourownbotnet import create_app
  File "/home/jujubunz/byob/web-gui/buildyourownbotnet/__init__.py", line 2, in <module>
    from flask import Flask
ModuleNotFoundError: No module named 'flask'

I tried installing the requirements.txt 
if anyone could help me out that would be great! Thanks!
@malwaredllc

**Comment by xer0xde** [comment]
same bug

**Comment by Collinsbrown7723** [comment]
Same here ✋

**Comment by JuJuBunz** [comment]
I think it has to do with pip, currently trying to figure it out.

**Comment by JuJuBunz** [comment]
I believe it has to do with numpy

**Comment by GoofyLean** [comment]
The project is dead. try a older version of flask.

**Comment by WaldperlachFabi** [comment]
Same here

**Comment by zaylusz** [comment]
Do ' sudo pip3 install flask ' im pretty sure thats how you typed it out.

**Comment by ppaauuoo** [comment]
I use anaconda on window and it works.

**Comment by DanceMonkey276** [comment]
Are you using a virtual environment? I had the same issue and that helped. I deleted everything, reinstalled it, set up the virtual environment and ran the startup.sh file again.

**Comment by Tytan-Codes-Alt** [comment]
WOW, yall dumb. 

```
# use pip or pip3
pip3 install flash 
```

**Comment by DanceMonkey276** [comment]
The problem is, when it doesn‘t have Flask installed, there was a error installing the requirements, so none of them are installed. You would have to manually install every requirement but this would lead to version issues (certain packages need other versiona of other packages, so the other version will be overwritten)
JuJuBunz, did you get any errors while running the startup.sh script? If you did, could you inform us about these?

**Comment by ThePuteh** [comment]
> WOW, yall dumb.
> 
> ```
> # use pip or pip3
> pip3 install flash 
> ```

flask the Flash ... 👍
