### ISSUE TITLE
run.py typeerror

### ISSUE THREAD

**Issue by Kukikano0709** [malwaredllc/byob#698]
Traceback (most recent call last):
  File "run.py", line 1, in <module>
    from buildyourownbotnet import create_app
  File "/root/byob/web-gui/buildyourownbotnet/__init__.py", line 2, in <module>
    from flask import Flask
  File "/usr/local/lib/python3.8/dist-packages/flask/__init__.py", line 5, in <module>
    from . import json as json
  File "/usr/local/lib/python3.8/dist-packages/flask/json/__init__.py", line 6, in <module>
    from ..globals import current_app
  File "/usr/local/lib/python3.8/dist-packages/flask/globals.py", line 25, in <module>
    app_ctx: AppContext = LocalProxy(  # type: ignore[assignment]
TypeError: __init__() got an unexpected keyword argument 'unbound_message'

**Comment by Pleasurecruise** [comment]
The same problem.Wait for answer.

**Comment by Aerialflame7125** [comment]
From: [](https://stackoverflow.com/questions/73337927/typeerror-init-got-an-unexpected-keyword-argument-unbound-message)

Comment 1. "I had an older version of Werkzeug in my requirements.txt that needed removing"
Fix 1. Upgrade Werkzeug
Comment 2. "I added flask==2.1.3 to my requirements and it worked. I think this is a problem with the currently lastest versions of flask"
Fix 2. **DO NOT** use version listed here, just upgrade flask

Lesson Learned, ### **DO YOUR RESEARCH FIRST**
